### ISSUE TITLE
Please add HVV to transportr

### ISSUE THREAD

**Issue by ghost** [grote/Transportr#123] opened 2015-11-16 13:43 UTC
HVV lets developers use their API, if requested:
- http://www.hvv.de/fahrplaene/fahrplanauskunft/datenschnittstelle/index.php

Could you please add HVV for public transportation in Hamburg to transportr?

**Comment by grote** [comment] 2015-11-16 22:49
There is a problem with HVV which is why it is disabled. I don't remember the details, but maybe @schildbach knows more. For Hamburg, you can use other providers such as SH or GVH.

**Comment by schildbach** [comment] 2015-11-16 23:40
The problem is simply nobody has implemented an adapter for the API.

**Comment by bjoernb** [comment] 2015-11-18 12:25
I just asked HVV via their contact formular to open up the API to be accessible for everyone.

**Comment by bjoernb** [comment] 2015-11-27 23:44
This is the answer from HVV in german:

    <Anrede>
    
    vielen Dank für Ihr Interesse an unseren Daten zur HVV-Auskunft.
    
    Die Daten werden von uns kostenlos über die API-Schnittstelle oder im
    Rohdatenformat zur Verfügung gestellt.  Auf Wunsch der
    Verkehrsunternehmen ist die Weitergabe jedoch aktuell nur mit einer
    unterschriebenen Nutzervereinbarung möglich.
    
    Anbei erhalten Sie die dazugehörige API-Schnittstellenbeschreibung
    (GTI) als Vorabinformation.  Sollten Sie weiterhin Interesse an einem
    Zugang haben, lasse ich Ihnen gerne unseren Vertrag für die
    (kostenlose) Nutzung zukommen.  Bitte nennen Sie uns hierfür Ihre
    Adresse sowie den gewünschten Zeitumfang der Testphase (mindestens 1
    Monat).
    
    Alternativ haben Sie wie gesagt auch die Möglichkeit Rohdaten in den
    Formaten GTFS, ISA und Transform zu erhalten.  Für die Bereitstellung
    der Daten ist ebenfalls eine Nutzervereinbarung nötig, für die ich
    Ihre Adresse benötige.
    
    <Verabschiedung>

**Comment by grote** [comment] 2015-11-28 13:54
> I do not get, why they need the personal data of the users of their
> API. Why don't they just have a public API that anyone can access?

That is a question you should probably ask them.

AFAIK, the biggest problem at the moment is not the non-public API, but that there's nobody implementing a HVV provider for the public transport enabler.

**Comment by bjoernb** [comment] 2015-12-11 11:06
Still no answer from HHV to that question.

**Comment by adundovi** [comment] 2016-09-17 05:49
Hello, I'm willing to study how to implement the enabler for HVV, yet I don't know where to start if we don't have an access to the API?

tcpdump of the official HVV app gave me the hint that the API server is
https://fiffi2.fahrinfoapp.de
but as it is under SSL, I cannot extract more information.

**Comment by grote** [comment] 2016-09-18 17:00
You could try [mitmproxy](https://mitmproxy.org/) to peek into the traffic.

**Comment by adundovi** [comment] 2016-09-20 15:25
@grote I don't understand how could I have any benefit of using it when the traffic goes over HTTPS, or am I missing something?

**Comment by grote** [comment] 2016-09-20 15:33
You would need to add a self-signed certificate to your Android trust-store and use this for the proxy. I doubt they do certificate pinning in their app. This procedure might violate your local law. Use at your own risk.

**Comment by spaetz** [comment] 2016-10-26 06:01
Hi, the fahrinfoapp.de site seems to be a 3rd party provider that the HVV app uses. I am not sure, they will have a great interest in letting others use their API. So that seems to be a different data source than the official HVV data API that they advertize on the hvv.de site.

@ghost has received the API documentation from HVV. If he applies for an API account, one could try to get an interface working. My understanding is that they require an account so that they can monitor who uses how much data and be able to shut down apps/accounts that abuse the API. In that sense it *migh*t be possible to embed the transportr credentials in the source  code (depending on their terms of service).

**Comment by Echolon** [comment] 2017-06-05 20:13
Why isnt Deutsche Bahn (for whole Germany) not enough? Or not enough for Hamburg? I still don't get why people use local apps...

**Comment by spaetz** [comment] 2017-06-07 05:01
@Echolon, because the HVV frequently gives better results than the Bahn service? Because the Bahn service proposes to autocomplete station names for totally different regions, for example?

**Comment by Echolon** [comment] 2017-10-30 11:08
Maybe interesting: http://suche.transparenz.hamburg.de/dataset/hvv-fahrplandaten-gtfs-september-2017-bis-dezember-2017 and in general a good step: https://rettedeinennahverkehr.de/

Thus, Hamburg finally follows their transparency laws.

**Comment by adundovi** [comment] 2017-10-31 13:36
Hmm, but this is not the real-time data, only the timetables, right?

**Comment by grote** [comment] 2018-07-26 21:10
This ticket is quite old and nobody took it up. I am not living in this city and can't do it. Let's close it until someone has added support for this city in public transport enabler.

As a reminder, the process for adding support for a new region is described on the homepage: https://transportr.app/contribute/#translating-into-your-language

**Closed by grote** 2018-07-26 21:10 UTC
Labels: coverage 🗺️, enhancement 🏗️, upstream 🏞️

**Comment by kadde1968** [comment] 2018-11-11 11:54
Now, their is a Link on navitia.io for the HVV with a dataset:
de_ohm_hamburg.zip. Does this help?
I don't how to add it to Transportr.
