### ISSUE TITLE
Add Esperanto, another small bugs (untranslateable countries, settings page, rename Poland, Warsaw)

### ISSUE THREAD

**Issue by verdulo** [grote/Transportr#212] opened 2016-07-06 17:01 UTC
1. Esperanto translation will be completed soon, please add it to the program. If it is possible please use 24h-system, coma (,) as decimal separator, and date format YYYY-MM-DD.

2. There is bug in displaying names of countries and cities - they are always in language of the Android, instead in selected language.

3. Please add small (few pixels) left margin in "Settings" view, now letters on the edge of the screen looks bit ugly.

4. Please considering renaming "Poland, Warsaw" to "Poland", because "Poland, Warsaw" suggest that PKP is local transport provider in Warsaw, while in reality it is transport provider for the whole country.

**Comment by grote** [comment] 2016-07-06 17:11
> Esperanto translation will be completed soon, please add it to the program.

Awesome thanks a lot! :) I will pull the translations before the next release. No need to open issues for it.

> If it is possible please use 24h-system, coma (,) as decimal separator, and date format YYYY-MM-DD.

I don't do this myself. This is set automatically by Android. I don't know if Android handles Esperanto properly though.

> There is bug in displaying names of countries and cities - they are always in language of the Android, instead in selected language.

Do you have a screenshot for that?

> Please add small (few pixels) left margin in "Settings" view, now letters on the edge of the screen looks bit ugly.

The settings UI is generated by Android. Do you have a screenshot for that?

> Please considering renaming "Poland, Warsaw" to "Poland", because "Poland, Warsaw" suggest that PKP is local transport provider in Warsaw, while in reality it is transport provider for the whole country.

Does it maybe have special coverage for Warsaw while it doesn't have it for other cities?

In the future, please open one ticket per issue.

**Comment by verdulo** [comment] 2016-07-06 17:44
1. Esperanto is not supported by Android itself, I guess that "Cancel" and "OK" buttons cannot be translated too...

2. System language: Polish, selected language in options is English, (translated) names are still in Polish, I've tried to restart the phone after changing language version and killing the app, but problem still occurs:
![screenshot_2016-07-06-19-25-43](https://cloud.githubusercontent.com/assets/16842967/16628034/c04970ee-43a7-11e6-8728-d4871b087c88.png)
If you change language to any other, the names are still in Polish. Now I noticed that even string "Pick a transport network" is sometimes in Polish...

3. ![screenshot_2016-07-06-19-25-01](https://cloud.githubusercontent.com/assets/16842967/16628110/14cd5b4e-43a8-11e6-9c57-771641f432dc.png)

4. PKP is main railway operator in Poland:https://en.wikipedia.org/wiki/Polish_State_Railways.

O.K. The next time I'll open few small tickets instead.

**Comment by grote** [comment] 2016-07-06 23:46
> Esperanto is not supported by Android itself, I guess that "Cancel" and "OK" buttons cannot be translated too...

That's a shame. I don't know about date format and stuff, but you can create an issue for translating OK and Cancel. That's very easy.

> Polish, selected language in options is English, (translated) names are still in Polish, I've tried to restart the phone after changing language version and killing the app, but problem still occurs:

Hmm.. I can reproduce this, but only when the network picker was opened once and the language changed afterwards. It seems to happen more often. Very strange. You can open a dedicated issue for that.

> [Settings Screenshot]

Damn! This wasn't like this before. Like the white dialogs this is caused by an upgrade to the latest Android support libraries :( Seems only to happen on older phones though.

> PKP is main railway operator in Poland:https://en.wikipedia.org/wiki/Polish_State_Railways.

Ok so we should just remove Warsaw and instead say "Railways in Poland"?

**Comment by verdulo** [comment] 2016-07-09 21:18
I'll create additional tickets, yes the name can be: "Poland, railways in Poland".

**Comment by grote** [comment] 2016-07-09 21:56
> I'll create additional tickets

Thanks a lot! The settings style issue should be solved now by downgrading the support libraries.

> yes the name can be: "Poland, railways in Poland".

Did you know that you can do simple edits like these yourself directly from GitHub's webinterface without knowing any git? Wanna try? ;)

**Comment by grote** [comment] 2016-09-04 15:31
resolved by 66eba19e96e40de53ef8760c0fbf791187dbb98f

**Closed by grote** 2016-09-04 15:31 UTC
Labels: needs info
