### ISSUE TITLE
NullPointerException: null when searching

### ISSUE THREAD

**Issue by MCMic** [grote/Transportr#426] opened 2018-03-07 13:37 UTC
Hello,

I installed the app from f-droid on lineageos and tried to use it for south-east of France but I only get «NullPointerException: null» showing after a loading pop-up for a short time.
Any idea what could go wrong? Is that a known bug?

**Comment by grote** [comment] 2018-03-07 17:29
Could you try [2.0.0 beta 3](https://transportr.grobox.de/#testing_beta) and see if the same problems appears there? 

But it looks like this might be a duplicate of or at least closely related to schildbach/public-transport-enabler#94

**Comment by grote** [comment] 2018-03-07 17:31
@thony8 has made a pull request here schildbach/public-transport-enabler#169 which would address the issue, but it still hasn't been merged.

**Comment by grote** [comment] 2018-07-26 21:46
I'll close this here since this needs to get fixed in PTE.

**Closed by grote** 2018-07-26 21:46 UTC
Labels: bug 🐞, upstream 🏞️
