### ISSUE TITLE
Calendar is not installed

### ISSUE THREAD

**Issue by Saturdaynightlife** [grote/Transportr#828] opened 2022-09-02 19:09 UTC
When trying to save an Entry to my calendar i geht the message 'no calendar installed :-( '. 
But there are several calendar apps installed in my phone likre 'business calendar'. What went wrong? How can I installiert a calendar?

I'd appreciate any hell.

**Comment by ialokim** [comment] 2022-09-02 19:51
Thanks for reporting! This is actually a duplicate of #795 which has already been addressed. The issue will be fixed in the next version of Transportr.

**Closed by ialokim** 2022-09-02 19:51 UTC
