### ISSUE TITLE
Menu crashing

### ISSUE THREAD

**Issue by eri451** [grote/Transportr#196] opened 2016-05-28 12:00 UTC
I updated recently from f-droid. Now the app crashes when i try to access the menu via the hamburger button

**Comment by grote** [comment] 2016-05-28 15:09
Could this be a duplicate of #190 or #194? Do you have Xposed installed? Do you know how to get a stack trace for more information?

**Comment by grote** [comment] 2016-06-01 14:46
Could you try 1.1.2-beta1 and see if this issue maybe got resolved?

**Comment by grote** [comment] 2016-07-01 21:19
No feedback for a month, so I'll close this.

**Closed by grote** 2016-07-01 21:19 UTC
Labels: bug, needs info
