### ISSUE TITLE
App crashes when opening "Germany" dropdown in country selection

### ISSUE THREAD

**Issue by oli-z** [grote/Transportr#194] opened 2016-05-23 18:23 UTC
Galaxy S5 G900F, Phoenix ROM, Lolipop
```
 java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
 	at android.util.PathParser$PathDataNode.addCommand(PathParser.java:335)
 	at android.util.PathParser$PathDataNode.nodesToPath(PathParser.java:260)
 	at android.graphics.drawable.VectorDrawable$VPath.toPath(VectorDrawable.java:1265)
 	at android.graphics.drawable.VectorDrawable$VPathRenderer.drawPath(VectorDrawable.java:950)
 	at android.graphics.drawable.VectorDrawable$VPathRenderer.drawGroupTree(VectorDrawable.java:931)
 	at android.graphics.drawable.VectorDrawable$VPathRenderer.drawGroupTree(VectorDrawable.java:927)
 	at android.graphics.drawable.VectorDrawable$VPathRenderer.draw(VectorDrawable.java:938)
 	at android.graphics.drawable.VectorDrawable$VectorDrawableState.updateCachedBitmap(VectorDrawable.java:705)
 	at android.graphics.drawable.VectorDrawable.draw(VectorDrawable.java:280)
 	at android.widget.ImageView.onDraw(ImageView.java:1148)
 	at android.view.View.draw(View.java:15114)
 	at android.view.View.updateDisplayListIfDirty(View.java:14048)
 	at android.view.View.getDisplayList(View.java:14071)
 	at android.view.View.draw(View.java:14838)
 	at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
 	at android.view.View.draw(View.java:15117)
 	at android.view.View.updateDisplayListIfDirty(View.java:14048)
 	at android.view.View.getDisplayList(View.java:14071)
 	at android.view.View.draw(View.java:14838)
 	at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
 	at android.widget.ListView.drawChild(ListView.java:3396)
 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
 	at android.widget.AbsListView.dispatchDraw(AbsListView.java:2594)
 	at android.widget.ListView.dispatchDraw(ListView.java:3391)
 	at android.widget.ExpandableListView.dispatchDraw(ExpandableListView.java:353)
 	at android.view.View.draw(View.java:15117)
 	at android.widget.AbsListView.draw(AbsListView.java:4083)
 	at android.view.View.updateDisplayListIfDirty(View.java:14048)
 	at android.view.View.getDisplayList(View.java:14071)
 	at android.view.View.draw(View.java:14838)
 	at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
 	at android.view.View.updateDisplayListIfDirty(View.java:14043)
 	at android.view.View.getDisplayList(View.java:14071)
 	at android.view.View.draw(View.java:14838)
 	at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
 	at android.view.View.updateDisplayListIfDirty(View.java:14043)
 	at android.view.View.getDisplayList(View.java:14071)
 	at android.view.View.draw(View.java:14838)
 	at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
 	at android.view.View.updateDisplayListIfDirty(View.java:14043)
 	at android.view.View.getDisplayList(View.java:14071)
 	at android.view.View.draw(View.java:14838)
 	at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
 	at android.view.View.updateDisplayListIfDirty(View.java:14043)
 	at android.view.View.getDisplayList(View.java:14071)
 	at android.view.View.draw(View.java:14838)
 	at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
 	at android.view.View.updateDisplayListIfDirty(View.java:14043)
 	at android.view.View.getDisplayList(View.java:14071)
 	at android.view.View.draw(View.java:14838)
 	at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
 	at android.view.View.updateDisplayListIfDirty(View.java:14043)
 	at android.view.View.getDisplayList(View.java:14071)
 	at android.view.View.draw(View.java:14838)
 	at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
 	at android.view.View.draw(View.java:15117)
 	at android.widget.FrameLayout.draw(FrameLayout.java:592
```

**Comment by oli-z** [comment] 2016-05-23 18:29
Brazil and Austria are also not working

**Comment by grote** [comment] 2016-05-23 18:45
Do you use Xposed? Do you know how to get stack traces?

**Comment by oli-z** [comment] 2016-05-23 19:04
Yes, I have Xposed and Wanam installed. I don't know how to get stack traces

**Comment by grote** [comment] 2016-05-23 19:18
I suspect then that this is a duplicate of #190. Can you somehow try again without Xposed?

If you are root you can for example use the CatLog app to get a stack trace for the crash.

**Comment by oli-z** [comment] 2016-05-23 19:53
I disabled Xposed by pressing the back button while booting but it doesn't work either. Here is the logcat: https://gist.github.com/anonymous/6a81a861057971a9d08cf58c3cb1312d
Strangely it only doesn't work for Germany, Brazil and Austria

**Comment by grote** [comment] 2016-05-23 19:58
Thanks for the stacktrace! Unfortunately, the end is missing. Could you provide the end as well, please?

**Comment by oli-z** [comment] 2016-05-23 20:01
https://gist.github.com/oli-z/74859b615018a3c76bbd6242af6e4af1

**Comment by grote** [comment] 2016-05-23 20:03
Strange that it just stops here at the end of `MultiPhoneWin`:
```
at com.android.internal.policy.impl.MultiPhoneWindow$MultiPhoneDecorView.dispatchDraw(MultiPhoneWin
05-23 21:59:41.699 26443-26443/de.grobox.liberario I/Process: Sending signal. PID: 26443 SIG: 9
```

**Comment by oli-z** [comment] 2016-05-23 20:07
Strange, it's not the upload, the logcat in Android Studio just stops there.
http://prnt.sc/b7l1si

**Comment by grote** [comment] 2016-05-23 20:22
Most likely a problem in Google's libraries. You can help by trying to find an issue that matches the stacktrace here: https://code.google.com/p/android/issues/list

**Comment by grote** [comment] 2016-05-30 00:10
Problem is here: https://code.google.com/p/android/issues/detail?id=78162

**Comment by grote** [comment] 2016-05-30 00:58
Please check the upcoming beta version if this is fixed.

**Closed** 2016-05-30 00:58 UTC
Labels: bug

**Comment by grote** [comment] 2016-07-01 21:48
Could you try the latest version and see if this issue maybe got resolved?

**Comment by oli-z** [comment] 2016-07-01 22:34
I upgraded to Android Marshmallow in the meantime and now it works perfecty.
