### ISSUE TITLE
NPE in some areas of France (missing color)

### ISSUE THREAD

**Issue by Niilos** [grote/Transportr#360] opened 2017-09-14 09:37 UTC
Version 1.1.8 stable
Region France sud-est

From "Gare Part-Dieu Vivier Merle" or places aroud it
To "Voiron gare routière nord"
filters : all transportation modes

Pressing the search button display the loading aniation and after that a toast containing "NullPointerException: nulll"

**Comment by grote** [comment] 2017-09-15 21:16
Thanks for reporting. I could reproduce the issue.

The log for the bug is here:

```
09-15 18:13:53.618 W/System.err: java.lang.NullPointerException
09-15 18:13:53.641 W/System.err:     at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787)
09-15 18:13:53.641 W/System.err:     at de.schildbach.pte.dto.Style.parseColor(Style.java:108)
09-15 18:13:53.641 W/System.err:     at de.schildbach.pte.FranceSouthEastProvider.getLineStyle(FranceSouthEastProvider.java:57)
09-15 18:13:53.641 W/System.err:     at de.schildbach.pte.AbstractNavitiaProvider.parseLineFromSection(AbstractNavitiaProvider.java:420)
09-15 18:13:53.641 W/System.err:     at de.schildbach.pte.AbstractNavitiaProvider.parseLeg(AbstractNavitiaProvider.java:480)
09-15 18:13:53.641 W/System.err:     at de.schildbach.pte.AbstractNavitiaProvider.parseQueryTripsResult(AbstractNavitiaProvider.java:563)
09-15 18:13:53.641 W/System.err:     at de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:978)
```

**Comment by thony8** [comment] 2017-10-01 15:12
I created a Pull Request for the Public Transport Enabler (cf https://github.com/schildbach/public-transport-enabler/pull/169)
The reason is when the route use the train routes (SNCF for France), there is no hex color referenced in the SNCF GTFS (used by Navitia), causing NPE. I added a default color when it is "SNCF" for FR-SE

**Comment by grote** [comment] 2017-11-01 21:36
@thony8 please poke at the upsteam pull request to get it merged. I am closing this ticket as one is enough.

**Closed by grote** 2017-11-01 21:36 UTC
Labels: bug, upstream
