### ISSUE TITLE
dead link on the website

### ISSUE THREAD

**Issue by easyKL** [grote/Transportr#378] opened 2017-11-07 12:55 UTC
while accesing: https://transportr.grobox.de/#contribute 
in the section: **Transport Network Logos**
_Here is an example of Brazil (BR)._ 
is pointing to: https://github.com/grote/Transportr/blob/master/res/drawable/network_br_logo.xml
DEAD!

please replace with: https://github.com/grote/Transportr/blob/master/artwork/networks/network_br_logo.svg

**Comment by grote** [comment] 2017-11-07 12:56
Thanks for the report, however this looks like a duplicate of grote/Transportr-website#2

**Closed by grote** 2017-11-07 12:56 UTC
