### ISSUE TITLE
"Kind of transportation" dialog in dark mode broken

### ISSUE THREAD

**Issue by daniel-edler** [grote/Transportr#218] opened 2016-07-12 19:40 UTC
I think at least my version (1.1.3 from f-droid) might have an bug. If I open this dialog where I can choose which kind of transportation the software/api may consider for my trip I see a white dialog. Since I use the dark theme the font and the symbols are also white. That's not very user friendly ;-) . The last version I know it showed the dialog with "more contrast" was 1.1.1

Btw. good job :+1:

**Comment by grote** [comment] 2016-07-12 19:46
Thanks Daniel! :smile: 

This however is a duplicate of #209.

**Closed by grote** 2016-07-12 19:46 UTC

**Comment by daniel-edler** [comment] 2016-07-12 20:51
Sorry, my fault. I searched only in the set of open issued
