### ISSUE TITLE
clear / weed out / sort the history of stops

### ISSUE THREAD

**Issue by sebalis** [grote/Transportr#343] opened 2017-04-11 03:34 UTC
For an app that says it wants to preserve my privacy (and I know that this is a heartfelt issue for the developers), I am surprised that I can’t find a way of clearing the list of previously used stops. It also makes sense for decluttering, not just privacy. I would like to not just clear the whole list but also individual entries if I press and hold them. Maybe pressing and holding an entry should not open a sub-menu but initiate a dragging action where dragging to the side would mean removing the entry and dragging up or down would change the entry’s position in the history.

**Comment by grote** [comment] 2017-04-13 21:27
This sounds like a duplicate of #74. Can you confirm?

**Comment by sebalis** [comment] 2017-04-13 23:57
Yes, it is. But I would again like to stress that this is a potential privacy issue (I would like to show off Transportr to friends, but I don’t necessarily want them to see which stops I’ve used). And note the specific suggestion of gestures in this ticket. :-)

**Comment by grote** [comment] 2017-04-16 14:23
Please feel free to copy anything you want to add to #74 there. Otherwise, it does have a reference to this ticket now as well.

**Closed by grote** 2017-04-16 14:23 UTC
Labels: duplicate
