### ISSUE TITLE
In From-To view, putting the cursor on the From and choossing Home/Work, puts it in the To

### ISSUE THREAD

**Issue by Porrumentzio** [grote/Transportr#697] opened 2020-08-24 09:18 UTC
**Describe the bug**
In From-To view when selecting a travel itinerary, putting the cursor on the From and choosing Home/Work shortcuts/markers, puts it in the To, not on From as it should be.

**To Reproduce**
1. Go to "travel" symbol (an inverted `Enter` symbol)
2. Tap on From
3. Tap on Home shortcut/marker below
4. It is added to "To" side.

**Expected behavior**
If the cursor is in From and tapping in a shortcut/marker, it should appear where the cursors is in: From side.

**Screenshots**
![ScreenRecord-2020-08-24-11-14-36](https://user-images.githubusercontent.com/61913683/91026723-6eff5280-e5fb-11ea-9484-1d05ade2637a.gif)

**Versions (please complete the following information):**
 - **Transportr Version:** 2.0.1
 - **Device:** Xiaomi Redmi Not 4 X
 - **Android Version:** /e/OS Nougat (7.1.2)

**Comment by ialokim** [comment] 2020-08-24 10:25
This is a duplicate of #605. Please follow up the discussion over there.

**Closed by ialokim** 2020-08-24 10:25 UTC
Labels: bug 🐞, duplicate ➿
