### ISSUE TITLE
HslProvider: UnexpectedRedirectException since 1.1.7

### ISSUE THREAD

**Issue by montanari** [grote/Transportr#313] opened 2017-02-08 12:12 UTC
Hi,

After upgrading to version 1.1.7 I am no longer able to search any itinerary because of an UnexpectedRedirectException. This happens both if I pass the exact bus station or a location from the map. Also, it does not seem to find any station when I type the first letters. I use the HSL Helsinki network.

Removing 1.1.7 and installing 1.1.6 everything works again.

Thanks!

![screenshot_2017-02-08-14-00-53](https://cloud.githubusercontent.com/assets/7151042/22736690/25f2a73e-ee08-11e6-901a-632806b2f99d.png)

**Comment by grote** [comment] 2017-02-08 12:15
@msjoberg Looks like a recent PTE update broke the `HslProvider`. Can you confirm?

@montanari Thanks for the report. Technically, this ticket should be filed against PTE, but we can leave it here for the time being. Maybe @msjoberg has a quick fix available. Please stay on 1.1.6 until there's a fix.

**Comment by msjoberg** [comment] 2017-02-08 19:16
@grote In fact I noticed this problem myself just today. I'm also running 1.1.7. I haven't yet had time to investigate tho root cause.

I will try to make some time in the weekend to investigate. No time before that I'm afraid.

**Comment by msjoberg** [comment] 2017-02-14 20:23
I believe I have now fixed the problem in PTE (see [my pull request](https://github.com/schildbach/public-transport-enabler/pull/143)). My unit tests (included in PTE, but apparently nobody checks them!) failed with the same error, and after the fix they are all successful. I haven't tested it with Transportr, though.

**Comment by grote** [comment] 2017-04-02 15:08
This should be fixed with the latest 1.1.8 release. Please let me know if it isn't!

**Closed by grote** 2017-04-02 15:08 UTC
Labels: bug, upstream
