### ISSUE TITLE
New data for Spain causing problems // Update description

### ISSUE THREAD

**Issue by tenminutemail** [grote/Transportr#264] opened 2016-11-29 11:32 UTC
Hi there,

Navitia [published a lot of new datasets](https://groups.google.com/forum/#!topic/navitia/AhgKV4Isza8) for Spain. _Navitia playground_ contains a complete list of all datasets now available. 

- I tried the new datasets in Navitia playground and all of them work fine. 
- In Transportr however, some cities work, others don't or only partially (which is the case of Barcelona and Madrid). I get this error message: "NullPointerException: Attempt to invoke virtual method 'int.de.schildbach.pte.d-to.Product.ordinal()' on a null object reference". It would be nice to find a solution for this, so that the app becomes fully usuable in all the cities included as of now.

I don't know any code, so help would be appreciated.

- Also, the description of which cities and networks are included in Transportr should be updated. I'd propose something like this: Madrid (EMT, Metro, Cercanías, Tranvía, Buses urbanos & interurbanos), Barcelona (TMB, FGC), Basque Country, Mallorca (CTM), Menorca (CIME), Valencia (EMT, Metro), Alicante (TRAM), Tenerife (Tranvía, TITSA), La Palma (TILP)

Cheers

**Comment by patkan** [comment] 2016-12-02 10:47
Hi @tenmimutemail could you please add some directions on how to reproduce the observed exception?
By entering arbitrary names I could successfully use Madrid. (See station names in screenshot)
I did however test only this.


![tmp_15343-screenshot_2016-12-02-11-44-25-195152541](https://cloud.githubusercontent.com/assets/4189642/20831367/f052993a-b884-11e6-88ee-634b6283bd0e.png)

**Comment by tenminutemail** [comment] 2016-12-02 16:48
Hi @patkan, thanks a lot for you reply.

If I try to use Transportr in Madrid, Barcelona or Valencia it works for some connections, for others it doesn't work and I get the error message with the NullPointerException.

I tried the same route as you suggested for Madrid and it works just fine; now if I try to go, for example, from: "ALCALA-RETIRO, Madrid" to "ATOCHA, Madrid" the app gives me an error message (I get the same error in Barcelona: for example "Pg Bonanova, Barcelona" to "Vall d'Hebron, Barcelona").

If I try the same connection from Alcala-Retiro to Atocha in Navitia playground it works:

![navitia](https://cloud.githubusercontent.com/assets/23173049/20841846/96b47368-b8b5-11e6-977a-4f4beedf97c5.png)

As you can see in the screenshot from Navitia, it isn't clear which type of transport (bus, train, metro, etc.) is used. So there is a question mark for line 1 and 2. Maybe the problem is related to this.

**Comment by grote** [comment] 2016-12-03 17:37
The problem is that the API does not return a product which is unexpected and should be fixed on the API side. See journey 0 in your screenshot for an example.

I'll still prepare a fix for that in Transportr.

**Closed** 2016-12-03 18:14 UTC
Labels: bug

**Comment by tenminutemail** [comment] 2016-12-05 17:32
Thanks a lot @grote

**Comment by grote** [comment] 2016-12-05 17:43
@tenminutemail 1.1.6-beta2 got released over the weekend. Please test if it resolves all issues with the SpainProvider.

**Comment by tenminutemail** [comment] 2016-12-05 18:49
@grote Yes, it works fine! Thanks a lot, that's really awesome. 

There is just one minor design issue; as there is no bus (or train, metro etc.) symbol next to the number, the whole symbol looks a bit unproportional. See the S1 and S2 symbol in the screenshot. Is there a way to fix that?

Did you consider updating the network info (and cities) I proposed in my first post?

![transportr](https://cloud.githubusercontent.com/assets/23173049/20897618/625aab44-bb23-11e6-859d-da135cda5ba7.png)

**Comment by grote** [comment] 2016-12-05 19:00
I had updated the description, but forgot your nice list. Could you create a new ticket for that or even update it yourself? The convention we use so far is to first list all the cities and then the transport networks.

The problem with the missing icons is because there's no product returned from Navitia. Somebody should get in touch with them and see if they can fix this.

**Comment by tenminutemail** [comment] 2016-12-05 20:04
#267 Here is the PR, I hope that's fine.

I'll try to contact Navitia as well.

**Comment by grote** [comment] 2016-12-05 20:23
Thanks! :)

When contacting Navitia you might also want to bring up the issue that many stations are upper-case (not only for Spain). It would be nice if they could normalize these names to proper capitalization when importing the datasets.

**Comment by tenminutemail** [comment] 2016-12-08 11:56
Hi @grote 

I've contacted Navitia and they have already fixed it. So now, a train, bus, tram symbol is displayed when looking up a connection.

They'll also try to normalize the station names and try to implement proper capitalization.

**Comment by tenminutemail** [comment] 2016-12-08 12:08
I just realised that there is one more problem with the new data.

If I look up departures for one stop in Navitia, I get this result:

![departure](https://cloud.githubusercontent.com/assets/23173049/21009437/d6ad9540-bd46-11e6-88f9-cb72c27da9f8.png)

In Transportr, the data misbehaves and I get this result, where one train lines is only going into one direction and the other train line only goes into the other direction:

![dep2](https://cloud.githubusercontent.com/assets/23173049/21009496/39a260fe-bd47-11e6-82d5-d05731ce97db.png)

**Comment by grote** [comment] 2016-12-08 12:21
Thanks for getting them to fix the products issue. Regarding the line destination of departures, please open a dedicated ticket about that. I am not sure, but this might belong to PTE.
