### ISSUE TITLE
Search is not "Today" if the app is kept open for more than one day

### ISSUE THREAD

**Issue by dstaubsauger** [grote/Transportr#255] opened 2016-11-06 10:39 UTC
When you don't close the app and leave it open for several days, the date selection menu will still show "today", but it will search for connections on the day it was opened. This is especially bad if you open the app on a weekday and then search for connections on the weekend, because the schedule often differs.

**Comment by grote** [comment] 2016-11-06 12:13
Oh thanks for reporting this! Are you sure it is not using the current day for the search? If it doesn't this is a bug. So "Today" is not misleading, but not working as it should ;)

**Comment by grote** [comment] 2016-11-06 12:50
I could not reproduce this. Tried my test phone which had the app still open and tried also opening the app, changing the date of the phone, then returning to the app and searching. In both cases, the current day was used for the search.

**Comment by dstaubsauger** [comment] 2016-11-07 23:39
So, i tried it again. Steps to reproduce:
1. It's 23:00h. Search for some connection "today".
2. Open one of the connections (so you see which bus to take when etc.)
3. Stop using the app, do something else / switch phone screen off / etc.
4. After 00:00h, open the app again, and tap "back" until you are at the starting screen again.
5. It shows "Today". (←this is the bug)
6. If you tap it and exit the date selection popup (without changing), it will show yesterday's date instead of "today".

All steps on a real phone with an actual date change (no simulation/date editing involved). Android 4.2.2

**Comment by grote** [comment] 2016-11-07 23:52
Thanks for providing steps to reproduce this!

Did you actually search or just tap on today and check the date there? This time might indeed not be updated, but the actual search should be performed with the proper data. You can see the date of the connection in the connection details when tapping one of the found trips.

I'll see if I can also update the date shown in the dialog.

**Comment by Dominik-K** [comment] 2016-11-12 13:30
It's also an issue with the actual search. We stumbled over it today (weekend), as the schedule also differs at the weekend. Fortunately, we had enough time buffer and could easily catch the connecting train.

Happened with the GVH provider. As I checked the date, last Tuesday was shown.

**Comment by grote** [comment] 2016-11-13 12:39
Very strange! Which version are you using? Did you make a screenshot of the date that you checked?

**Comment by cookietime--yay** [comment] 2016-11-15 14:31
I got the same issue. I use version 1.1.5 from the F-Droid repo and the VGN backend.
Unfortunately I didn't make a screenshot, but it happened today (15. Nov) and it used the 13. Nov (last Sunday) for the search instead of the correct date.

**Comment by grote** [comment] 2016-11-30 19:54
Did you try 1.1.6-beta1 if the problem still persists there? Instructions for getting beta releases are on the homepage.

**Comment by grote** [comment] 2016-12-03 18:52
Ok there was a bug that only used the current time and date if they were set to "now" **and** "today". If one of them was not set, you might have gotten an outdated time when searching.

Should be fixed in 1.1.6-beta2. Please test!

**Closed** 2016-12-03 18:52 UTC
Labels: bug, needs info
