### ISSUE TITLE
Add trip price in the search results

### ISSUE THREAD

**Issue by francescosoave** [grote/Transportr#637] opened 2019-10-21 12:33 UTC
**Acknowledgments**
Please check the following boxes with an `x` if they apply:
* [x] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [x] I am aware that Transportr is mostly developed by one person in their unpaid spare time.
* [maybe] I can help myself to get this feature implemented or know someone who wants to do it.
* [x] If I want to add support for a new region or country, I checked that this is already available in [public-transport-enabler](https://github.com/schildbach/public-transport-enabler/) and know the process [described on the Transportr homepage](https://transportr.app/contribute/#translating-into-your-language).

**Is your feature request related to a problem? Please describe.**
no, but I think it's useful information (feature seen in other apps)

**Describe the solution you'd like**
In the search results, display the total cost of each proposed result

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions you've considered. But please limit this ticket to one feature or use-case.

**Additional context**

**Comment by ialokim** [comment] 2019-10-21 12:36
Thanks for your suggestion, but this is a duplicate of #231 and already in development with PR #627.

**Closed by ialokim** 2019-10-21 12:36 UTC
