### ISSUE TITLE
Homescreen link for more destinations than only Home.

### ISSUE THREAD

**Issue by pascalwilhelm** [grote/Transportr#417] opened 2018-02-05 15:56 UTC
The functionality is already there, to "bring me home" with the homescreen shortcut.
It would be nice to be able to have the possibility to add additional shortcuts for other destinations.
Maybe including the corresponding network change?

**Comment by grote** [comment] 2018-02-16 18:39
You can already add entire trips (in v2 beta) or add another shortcut for a "work" location. Does this resolve the issue for you?

**Comment by pascalwilhelm** [comment] 2018-02-18 12:35
Well, this solves a bit. 
Immagine, having some different locations in different countries, where you are heading to regularly.
E.g. I have an office in Brussels, in Torino and in Zurich. At each place I have also an address where I stay. My clients are in several places. 
I would like to have a shortcut on the homescreen to bring me to these 6 destinations from the current location. 
An additional benefit would be. That the shortcut contains also the information about the network to use.
(This works as described in ÖFFI. But for other reasons I prefere Transportr).

**Comment by grote** [comment] 2018-02-18 17:32
Thanks for the explanation.

Allowing arbitrary homescreen locations and even changing the current transport network after clicking those, is more tricky and currently not planned by me. I am also worried that it confuses users when their transport network gets changed after pressing a home-screen shortcut (maybe accidentally).

**Comment by grote** [comment] 2018-07-26 21:44
Another problem: The launcher shortcut API on Android 8 has changed and is more restrictive.

**Comment by ialokim** [comment] 2020-10-07 06:59
This is a duplicate of #505 and related to #555, please follow the discussion over there.

**Closed by ialokim** 2020-10-07 06:59 UTC
Labels: duplicate ➿, enhancement 🏗️
