### ISSUE TITLE
Milan is not correctly covered

### ISSUE THREAD

**Issue by Airon90** [grote/Transportr#183] opened 2016-04-20 10:14 UTC
If I select two stations, i.e. "[Stazione Garibaldi M2 M5](https://www.wikidata.org/wiki/Q1087026)"-"[Duomo M1 M5](https://www.wikidata.org/wiki/Q2519375)" or "[Garibaldi Fs](https://www.wikidata.org/wiki/Q22815083)"-"[Dateo](https://www.wikidata.org/wiki/Q3460862)" (respectively underground and railway stations), the app doesn't show any transport and tells me just to walk

**Comment by grote** [comment] 2016-04-20 13:17
Are you referring to the Italy transport network? If so, the data for that is coming directly from Navitia. You see what it contains here: https://navitia.opendatasoft.com/explore/dataset/it/table/?sort=type_file

So if there's something missing that could be there, please contact them. Once they included the missing data, it will automatically be available in Transportr.

Since there's nothing here to do for this project, I will close this issue.

**Closed by grote** 2016-04-20 13:17 UTC
Labels: coverage, upstream

**Comment by Airon90** [comment] 2016-04-20 17:24
I refer to the transport network in Milan (Italy) and I know that all data Transportr use come from Navitia.
Sincerely, I don't think it is a problem of Navitia data as the app doesn't find **any route** between **any street or station** from Milan to Milan so I fear that data from Navitia have been badly implemented in Transportr.

**Comment by grote** [comment] 2016-04-21 01:00
Not all data in Transportr is coming from Navitia, but the `IT` network is.

I can reproduce your problem in the `IT` network. However, I don't think this is related to how Transportr implements the Navitia API. You are welcome to take this up with them. The API request Transportr is making is this one:

```
http://api.navitia.io/v1/journeys?from=stop_area%3AOMI%3ASA%3ACTP15666&to=stop_area%3AOMI%3ASA%3ACTP11490&datetime=20160420T215406&datetime_represents=departure&count=6&depth=0&walking_speed=1.12
```

You might want to check before if the public transport company serving this connection is actually [included in Navitia](https://navitia.opendatasoft.com/explore/dataset/it/table/?sort=type_file). That's where the data comes from: https://amat-mi.it/it/mobilita/dati-strumenti-tecnologie/dati-gtfs/

**Comment by Airon90** [comment] 2016-04-21 08:02
Ok, I will ask Navitia to check their data. Thank you very much for your technical information, as I'm not a coder but just an open data lover :)

**Comment by Airon90** [comment] 2016-04-23 09:03
For more information,  see https://groups.google.com/forum/#!topic/navitia/AcWiQbnUWaE ;)
