### ISSUE TITLE
in [France, Sncf service] it says "impossible to find starting point" or "impossible to find destination"

### ISSUE THREAD

**Issue by dok-prog** [grote/Transportr#774] opened 2021-08-25 07:06 UTC
Since the last update the [France > Sncf] service does not work as before.
- If make the request "City1 train station" to "City2 train station" I get an error : impossible to find the starting point.
- If I ask "City1" to "City2", it works but it adds also some walking or some bus because, I guess, it computes from the center of each city.
- If I ask "City1" to "City2 train station" I get another error : impossible to find destination.

**To Reproduce**
- for the starting point type for example "saint-denis" and choose "Saint-Denis station"
- for the destination point type Groslay and choose "Groslay station"
- result is an error
- than I correct Saint Denis to specify the city and not the station, same thing for Groslay and boom it works, but the results are obviously not the same.

**Expected behavior**
Return to how it was working before.

**Screenshots**
![Screenshot_20210825-084428_Transportr](https://user-images.githubusercontent.com/65195071/130742067-03fa5a27-77a9-43e9-a343-25f68632736d.jpg)
![Screenshot_20210825-084451_Transportr](https://user-images.githubusercontent.com/65195071/130742081-4487d2d8-4ccd-4af3-8929-4ba70e6f2c86.jpg)

**Versions (please complete the following information):**
 - **Transportr Version:** 2.1.2
 - **Device:** Samsung Galaxy A51
 - **Android Version:** 11

**Comment by ialokim** [comment] 2022-04-26 22:11
This might well have to do with changed IDs (you were using stations marked as favorite before). So might be related to #207.

**Comment by Altonss** [comment] 2023-05-22 10:48
It seems indeed a duplicate of #207, as I wasn't able to reproduce it (having not marked them as favorites).
So if this issue is a duplicate, it could be closed I think in favor of  #207 :)

**Closed** 2023-05-23 21:06 UTC
Labels: bug 🐞
