### ISSUE TITLE
split high-speed train category in two

### ISSUE THREAD

**Issue by sebalis** [grote/Transportr#337] opened 2017-04-11 03:03 UTC
There’s currently no way to exclusively enable/disable trains like ICE in Germany, Thalys in Benelux, etc. – a feature that users of other apps would expect. I would use terms like long-distance and high-speed or premium for the two categories.

**Comment by grote** [comment] 2017-04-13 21:16
This looks like a duplicate of #300 and is also discussed in schildbach/public-transport-enabler#136

**Closed** 2017-11-01 21:27 UTC
Labels: duplicate, upstream
