### ISSUE TITLE
Mark "ago" travel-times better to avoid confusions

### ISSUE THREAD

**Issue by Porrumentzio** [grote/Transportr#696] opened 2020-08-24 09:08 UTC
**Acknowledgments**
Please check the following boxes with an `x` if they apply:
* [x] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [x] I am aware that Transportr is mostly developed by one person in their unpaid spare time.
* [ ] I can help myself to get this feature implemented or know someone who wants to do it.
* [ ] If I want to add support for a new region or country, I checked that this is already available in [public-transport-enabler](https://github.com/schildbach/public-transport-enabler/) and know the process [described on the Transportr homepage](https://transportr.app/contribute/#translating-into-your-language).

**Is your feature request related to a problem? Please describe.**
When searching a travel and selecting a way/line, if pulled down there appears previous ways/lines, which **are already** in the **past**.
This past ways/lines are not distinguished in any way from the future ones, getting the user into confusion. 

**Describe the solution you'd like**
The **past** ways/lines could be distinguished using **another color**, clearly, and also **mark**ing with a thick line the **limit** between past and future ways/lines.

**Describe alternatives you've considered**
Past ways/lines could be **not** displayed.

**Additional context**
Actual state with light theme:
![irudia](https://user-images.githubusercontent.com/61913683/91025311-7b82ab80-e5f9-11ea-8534-00b79220bc56.png)

My proposal:
![Transportr_past_future](https://user-images.githubusercontent.com/61913683/91025718-0bc0f080-e5fa-11ea-8402-2eaaf5b68225.jpg)

**Comment by ialokim** [comment] 2020-08-24 10:21
Thanks a lot for your suggestions! This specific issue is a duplicate of #593. You might post your mockups again over there.

**Closed by ialokim** 2020-08-24 10:21 UTC
Labels: duplicate ➿, enhancement 🏗️
