### ISSUE TITLE
Crash on Start of App [2.0.7]

### ISSUE THREAD

**Issue by HostedDinner** [grote/Transportr#652] opened 2019-12-10 16:35 UTC
**Describe the bug**
Start the app after update to 2.0.7 (Google AppStore Version) crashes directly at startup. Is it a beta release? I'm in the beta program.

**To Reproduce**
1. Open app

**Versions (please complete the following information):**
 - **Transportr Version:** 2.0.7 (AppStore)
 - **Device:** Samsung S7, Stock Android, no Root, etc. (SM-G930F)
 - **Android Version:** 8.0.0 (Patch Level 1. Sep 2019, latest Update from Samsung Stock Version)

**Comment by grote** [comment] 2019-12-10 17:55
Thanks for the report! @ialokim will try to look into it tonight.

**Comment by ialokim** [comment] 2019-12-10 22:43
Okay, so what I've found out is the following: The crash is due to some error within the Room library which is used internally for the database. This is the stacktrace:
```
12-10 23:17:55.043 11448 11472 E AndroidRuntime: FATAL EXCEPTION: arch_disk_io_1
12-10 23:17:55.043 11448 11472 E AndroidRuntime: Process: de.grobox.liberario, PID: 11448
12-10 23:17:55.043 11448 11472 E AndroidRuntime: java.lang.RuntimeException: Exception while computing database live data.
12-10 23:17:55.043 11448 11472 E AndroidRuntime: 	at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:92)
12-10 23:17:55.043 11448 11472 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
12-10 23:17:55.043 11448 11472 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
12-10 23:17:55.043 11448 11472 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
12-10 23:17:55.043 11448 11472 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
12-10 23:17:55.043 11448 11472 E AndroidRuntime: 	at androidx.room.RoomOpenHelper.checkIdentity(RoomOpenHelper.java:154)
12-10 23:17:55.043 11448 11472 E AndroidRuntime: 	at androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:135)
12-10 23:17:55.043 11448 11472 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:142)
12-10 23:17:55.043 11448 11472 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:349)
12-10 23:17:55.043 11448 11472 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:238)
12-10 23:17:55.043 11448 11472 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:92)
12-10 23:17:55.043 11448 11472 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:53)
12-10 23:17:55.043 11448 11472 E AndroidRuntime: 	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:476)
12-10 23:17:55.043 11448 11472 E AndroidRuntime: 	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:281)
12-10 23:17:55.043 11448 11472 E AndroidRuntime: 	at androidx.room.RoomDatabase.query(RoomDatabase.java:324)
12-10 23:17:55.043 11448 11472 E AndroidRuntime: 	at androidx.room.util.DBUtil.query(DBUtil.java:83)
12-10 23:17:55.043 11448 11472 E AndroidRuntime: 	at de.grobox.transportr.data.locations.LocationDao_Impl$6.call(LocationDao_Impl.java:582)
12-10 23:17:55.043 11448 11472 E AndroidRuntime: 	at de.grobox.transportr.data.locations.LocationDao_Impl$6.call(LocationDao_Impl.java:579)
12-10 23:17:55.043 11448 11472 E AndroidRuntime: 	at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:90)
12-10 23:17:55.043 11448 11472 E AndroidRuntime: 	... 3 more
12-10 23:17:55.046  1608  8888 W ActivityManager:   Force finishing activity de.grobox.liberario/de.grobox.transportr.map.MapActivity
```

The issue does only arise for installations that started with version 2.0.0. It can be reproduced by installing version 2.0.0, opening the app once, selecting a network and then updating to the new 2.0.7 (might or not passing by intermediate version updates). If the first installed version is >= 2.0.1, the crash does not happen even after updating to 2.0.7.

As there haven't been any database scheme migrations since 2.0.0, I don't think https://developer.android.com/training/data-storage/room/migrating-db-versions#handle-default-values-migrations applies here (cf. the note at the end of the article). It is most probably due to some bug which has been fixed [within Room between 1.1.0 and 1.1.1](https://github.com/grote/Transportr/compare/2.0.0...2.0.1#diff-39e7d8c00954e920b98e7636f0ac30b2R113), but only turns out to be a problem with the new version 2.2.0.

Not sure how to cope with this @grote ?

**Comment by ialokim** [comment] 2019-12-10 22:52
This might be related to https://developer.android.com/jetpack/androidx/releases/room#2.2.0-beta01 though.

**Comment by grote** [comment] 2019-12-10 22:58
Awesome that you managed to find conditions to reproduce this! Good work!

We could try to upgrade Room and see if that helps. If not, maybe try the default migration even if they say it might not be required?

**Comment by grote** [comment] 2019-12-10 23:04
> Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.

This indicates that something *did* change along the way.

**Comment by grote** [comment] 2019-12-10 23:05
Maybe we can export a new JSON and compare it to [the old one](https://github.com/grote/Transportr/blob/master/app/schemas/de.grobox.transportr.data.Db/1.json)?

**Comment by ialokim** [comment] 2019-12-10 23:08
> This indicates that something _did_ change along the way.

Strange is that this doesn't happen neither between 2.0.0 and 2.0.1 nor between any version >= 2.0.1 and 2.0.7, so not sure whether there was really a change to the schema or just some inconsistencies between different room versions.

**Comment by HostedDinner** [comment] 2019-12-11 17:08
I had indeed installed prior versions, going back 1.x. And then just updated along with the AppStore updates. So I probably had 2.0.0 at some time.

**Comment by ialokim** [comment] 2019-12-16 22:58
This may be addressed by this recent bugfix: https://android.googlesource.com/platform/frameworks/support/+/40e267943a2398b9e4177f2642f9577455821ff6

> When calculating the legacy hash not only must IF NOT EXISTS be removed
from the CREATE INDEX statement, but an extra space has to be preserved
since versions of Room before 2.2 had such typo and is considered
during legacy hash calculations.

It has been merged 10 days ago.

**Comment by grote** [comment] 2019-12-17 11:02
Good find! So our options are to wait for this fix to get released or try to downgrade Room to the last version before 2.2?

**Comment by ialokim** [comment] 2019-12-17 22:17
True, I had forgotten this downgrading option.

I've tried it now changing Room back to version 2.0.0 as in Transportr 2.0.6 and it works, even for phones where the corrupted 2.0.7 has been installed before.

Should we build a new release with release number 2.0.8 (or 2.0.7.1 as basically nothing has changed except a big bugfix) or just sort of "republish" 2.0.7 as a corrected version? That of course would cause trouble for all those who had already installed the corrupted version before.

**Comment by grote** [comment] 2019-12-17 22:27
> Should we build a new release with release number 2.0.8

This! Thanks for testing the downgrade!

**Closed** 2019-12-18 12:54 UTC
Labels: bug 🐞

**Comment by ialokim** [comment] 2019-12-19 14:32
It has been released: https://developer.android.com/jetpack/androidx/releases/room#2.2.3

**Comment by grote** [comment] 2019-12-19 20:21
Nice, did you try if it fixes the problem as well?

**Comment by ialokim** [comment] 2019-12-20 17:20
Yes it does. Should we go for the new Room version then for this release or leave it as is?

**Comment by Lantus81** [comment] 2019-12-22 19:27
tnx, guys, this helped me to
