### ISSUE TITLE
dark theme shows blank calendar

### ISSUE THREAD

**Issue by soerenk** [grote/Transportr#223] opened 2016-07-31 17:24 UTC
While using the dark theme and open the calender to change the date it shows white letters on white ground. Only the date of today and the selected date are red/black. You can still change the date, but its a lucky guess.

**Comment by grote** [comment] 2016-07-31 23:05
Duplicate of #216 and #209 I'd say. Thanks anyway!

**Closed by grote** 2016-07-31 23:05 UTC
