### ISSUE TITLE
Highlight current / nearest stop in route

### ISSUE THREAD

**Issue by sedrubal** [grote/Transportr#651] opened 2019-12-09 16:31 UTC
**Acknowledgments**
Please check the following boxes with an `x` if they apply:
* [x] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [x] I am aware that Transportr is mostly developed by one person in their unpaid spare time.
* [ ] I can help myself to get this feature implemented or know someone who wants to do it.
* [ ] If I want to add support for a new region or country, I checked that this is already available in [public-transport-enabler](https://github.com/schildbach/public-transport-enabler/) and know the process [described on the Transportr homepage](https://transportr.app/contribute/#translating-into-your-language).

**Is your feature request related to a problem? Please describe.**
If your current route has many stops and you don't know the route well it's hard to find the current station.

**Describe the solution you'd like**
It would be useful if the nearest stop according to the current location would be highlighted in the list of stops.

**Additional context**

I think, Öffi does this, too.

**Comment by grote** [comment] 2019-12-10 14:40
Related to #399, if not a duplicate of it.

**Closed** 2020-09-06 21:12 UTC
Labels: duplicate ➿, enhancement 🏗️
