### ISSUE TITLE
More precise suggestions when entering a public transport stop

### ISSUE THREAD

**Issue by Zeralda** [grote/Transportr#596] opened 2019-03-16 10:07 UTC
**Acknowledgments**
Please check the following boxes with an `x` if they apply:
* [X] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [X] I am aware that Transportr is mostly developed by one person in their unpaid spare time.
* [ ] I can help myself to get this feature implemented or know someone who wants to do it.
* [ ] If I want to add support for a new region or country, I checked that this is already available in [public-transport-enabler](https://github.com/schildbach/public-transport-enabler/) and know the process [described on the Transportr homepage](https://transportr.app/contribute/#translating-into-your-language).

**Is your feature request related to a problem? Please describe.**
I often know the exact name of the stop I am looking for. Still, it does not appear at the top of the list, I have to scroll down several - sometimes several dozens - of entries to find the right place.

**Describe the solution you'd like**
When the entered text matches the name of a public transport stop exactly, show this stop at the top of the list.

**Comment by ialokim** [comment] 2020-09-06 21:00
This is related to #630, if not a duplicate of it.

**Closed by ialokim** 2020-09-06 21:00 UTC
Labels: duplicate ➿, upstream 🏞️
