### ISSUE TITLE
Calendar is not installed

### ISSUE THREAD

**Issue by Fuzzybear2** [grote/Transportr#846] opened 2023-03-07 15:22 UTC
I tried to save my  connection in my calendar. Then I get error message "No Calendar is installed"..

Android standard calendar is deactivated. I am using simple calendar instead. It should work nevertheless, shouldnt it?

Transporter 2.1.4, Android 11

**Comment by Altonss** [comment] 2023-03-07 15:27
This issue is a duplicate of https://github.com/grote/Transportr/issues/795, please search for already existing issues next time :)
The issue has been fixed, but the fix will only be available in the next version...

**Closed** 2023-04-04 11:30 UTC
Labels: bug 🐞, duplicate ➿
