### ISSUE TITLE
Sometimes no direction / connection found

### ISSUE THREAD

**Issue by vuyibiran** [grote/Transportr#134] opened 2015-12-07 09:05 UTC
Hello

Great program, thanks for your work!

About the problem:
Sometimes when searching for a connection I get the toast: no connection found. If I repeat the search 2 or 3 times Transportr suddenly shows the right connection.

It also happens the other way around: Searching for a connection gives a result. Going back to search screen and do the search again gives the toast.

To test you have to set up:
Deutsche Bahn Network, Germany
Enter for example:
From: Leipzig, Pittlerstraße
To: Leipzig, Wiesenrain anything.

I don't see anything in the log.

**Comment by grote** [comment] 2015-12-07 20:16
Unfortunately, I couldn't reproduce this. There must be *something* in the log.

**Comment by vuyibiran** [comment] 2015-12-08 08:55
First of all, I changed the heading, the error says: no directions found. Sorry about that.

I can reproduce it so I tried to capture the error in the log. Maybe it's useful.

Log:
-----
>I/Timeline( 4692): Timeline: Activity_idle id: android.os.BinderProxy@ac450c time:310083
W/ActivityManager(  644): getRecentTasks: caller 10058 does not hold REAL_GET_TASKS; limiting output
W/ActivityManager(  644): getTasks: caller 10058 does not hold REAL_GET_TASKS; limiting output
I/Timeline(  644): Timeline: Activity_windows_visible id: ActivityRecord{12961629 u0 de.grobox.liberario/.activities.MainActivity t117} time:310322
D/getLocationId( 4692): Found location: Location{STATION, 956045, 51376695/12313468, place=Leipzig, name=Pittlerstr.}
D/getLocationId( 4692): Found location: Location{ADDRESS, 51357701/12266715, place=Leipzig - Burghausen, name=Wiesenrain 22-27}
V/WindowManagerService(  644): not Base app: Adding window Window{20a564d9 u0 de.grobox.liberario/de.grobox.liberario.activities.MainActivity} at 3 of 7
D/AsyncQueryTripsTask( 4692): From: Location{STATION, 956045, 51376695/12313468, place=Leipzig, name=Pittlerstr.}
D/AsyncQueryTripsTask( 4692): To: Location{ADDRESS, 51357701/12266715, place=Leipzig - Burghausen, name=Wiesenrain 22-27}
D/AsyncQueryTripsTask( 4692): Date: Tue Dec 08 09:48:00 GMT+01:00 2015
W/InputMethodManagerService(  644): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@23fc3e9e attribute=null, token = android.os.BinderProxy@165d323f
V/RenderScript( 4692): Application requested CPU execution
V/RenderScript( 4692): 0xb772e360 Launching thread(s), CPUs 4
W/ActivityManager(  644): getRecentTasks: caller 10058 does not hold REAL_GET_TASKS; limiting output
W/ActivityManager(  644): getTasks: caller 10058 does not hold REAL_GET_TASKS; limiting output
E/QC-NETMGR-LIB(  195): Received nl msg, recvmsg returned 56
E/QC-NETMGR-LIB(  195): Processing RTM_NEWLINK
E/QC-NETMGR-LIB(  195): Metainfo:  Index=22 Family=0 Type=0x1 Change=[0x0] Flags=[0x11043]UP BROADCAST RUNNING MULTICAST LOWER_UP 
D/ALSADevice(  205): standby: handle 0xb79b3930 h 0x0

and also

> I/Timeline(  644): Timeline: Activity_windows_visible id: ActivityRecord{1da975f5 u0 de.grobox.liberario/.activities.TripsActivity t117} time:392928
D/OpenGLRenderer( 4692): endAllStagingAnimators on 0xb77e6450 (RippleDrawable) with handle 0xb7790888
I/Timeline( 4692): Timeline: Activity_idle id: android.os.BinderProxy@ac450c time:393543
I/Timeline(  644): Timeline: Activity_windows_visible id: ActivityRecord{12961629 u0 de.grobox.liberario/.activities.MainActivity t117} time:393796
D/getLocationId( 4692): Found location: Location{STATION, 956045, 51376695/12313468, place=Leipzig, name=Pittlerstr.}
D/getLocationId( 4692): Found location: Location{ADDRESS, 51357701/12266715, place=Leipzig - Burghausen, name=Wiesenrain 22-27}
V/WindowManagerService(  644): not Base app: Adding window Window{32996f3a u0 de.grobox.liberario/de.grobox.liberario.activities.MainActivity} at 3 of 7
D/AsyncQueryTripsTask( 4692): From: Location{STATION, 956045, 51376695/12313468, place=Leipzig, name=Pittlerstr.}
D/AsyncQueryTripsTask( 4692): To: Location{ADDRESS, 51357701/12266715, place=Leipzig - Burghausen, name=Wiesenrain 22-27}
D/AsyncQueryTripsTask( 4692): Date: Tue Dec 08 09:48:00 GMT+01:00 2015
W/ActivityManager(  644): getRecentTasks: caller 10058 does not hold REAL_GET_TASKS; limiting output
W/ActivityManager(  644): getTasks: caller 10058 does not hold REAL_GET_TASKS; limiting output
D/DirectionsFragment( 4692): QueryTripsResult{OK, size=4, trips=[Trip{C0-0, Tue 09:42, numChanges=2}, Trip{C0-1, Tue 09:42, numChanges=2}, Trip{C0-2, Tue 10:02, numChanges=2}, Trip{C0-3, Tue 10:02, numChanges=1}]}
I/Timeline( 4692): Timeline: Activity_launch_request id:de.grobox.liberario time:394938
I/ActivityManager(  644): START u0 {cmp=de.grobox.liberario/.activities.TripsActivity (has extras)} from uid 10059 on display 0
V/WindowManagerService(  644): addAppToken: AppWindowToken{2a8063e1 token=Token{38679948 ActivityRecord{c1437eb u0 de.grobox.liberario/.activities.TripsActivity t117}}} to stack=1 task=117 at 1
W/InputMethodManagerService(  644): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@181f4506 attribute=null, token = android.os.BinderProxy@165d323f
I/AppCompatViewInflater( 4692): app:theme is now deprecated. Please move to using android:theme instead.
D/getLocationId( 4692): Found location: Location{STATION, 956045, 51376695/12313468, place=Leipzig, name=Pittlerstr.}
D/getLocationId( 4692): Found location: Location{ADDRESS, 51357701/12266715, place=Leipzig - Burghausen, name=Wiesenrain 22-27}
V/WindowManagerService(  644): Adding window Window{20101f4 u0 de.grobox.liberario/de.grobox.liberario.activities.TripsActivity} at 4 of 8 (after Window{32996f3a u0 de.grobox.liberario/de.grobox.liberario.activities.MainActivity EXITING})
I/ActivityManager(  644): Displayed de.grobox.liberario/.activities.TripsActivity: +487ms
I/Timeline( 4692): Timeline: Activity_idle id: android.os.BinderProxy@3e2075e4 time:395474
I/Timeline(  644): Timeline: Activity_windows_visible id: ActivityRecord{c1437eb u0 de.grobox.liberario/.activities.TripsActivity t117} time:395826
D/OpenGLRenderer( 4692): endAllStagingAnimators on 0xb769aee8 (RippleDrawable) with handle 0xb7a42590
I/Timeline( 4692): Timeline: Activity_idle id: android.os.BinderProxy@ac450c time:396462
W/ActivityManager(  644): getRecentTasks: caller 10058 does not hold REAL_GET_TASKS; limiting output
W/ActivityManager(  644): getTasks: caller 10058 does not hold REAL_GET_TASKS; limiting output
I/Timeline(  644): Timeline: Activity_windows_visible id: ActivityRecord{12961629 u0 de.grobox.liberario/.activities.MainActivity t117} time:396699
E/QC-NETMGR-LIB(  195): Received nl msg, recvmsg returned 56
E/QC-NETMGR-LIB(  195): Processing RTM_NEWLINK
E/QC-NETMGR-LIB(  195): Metainfo:  Index=22 Family=0 Type=0x1 Change=[0x0] Flags=[0x11043]UP BROADCAST RUNNING MULTICAST LOWER_UP 
D/getLocationId( 4692): Found location: Location{STATION, 956045, 51376695/12313468, place=Leipzig, name=Pittlerstr.}
D/getLocationId( 4692): Found location: Location{ADDRESS, 51357701/12266715, place=Leipzig - Burghausen, name=Wiesenrain 22-27}
V/WindowManagerService(  644): not Base app: Adding window Window{3fd7e478 u0 de.grobox.liberario/de.grobox.liberario.activities.MainActivity} at 3 of 7
D/AsyncQueryTripsTask( 4692): From: Location{STATION, 956045, 51376695/12313468, place=Leipzig, name=Pittlerstr.}
D/AsyncQueryTripsTask( 4692): To: Location{ADDRESS, 51357701/12266715, place=Leipzig - Burghausen, name=Wiesenrain 22-27}
D/AsyncQueryTripsTask( 4692): Date: Tue Dec 08 09:48:00 GMT+01:00 2015
W/InputMethodManagerService(  644): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@23590751 attribute=null, token = android.os.BinderProxy@165d323f
W/ActivityManager(  644): getRecentTasks: caller 10058 does not hold REAL_GET_TASKS; limiting output
W/ActivityManager(  644): getTasks: caller 10058 does not hold REAL_GET_TASKS; limiting output


I also recorded a video about this - but it seems that it is not possible to add attachments?

**Comment by vuyibiran** [comment] 2015-12-08 09:01
[file.zip](https://github.com/grote/Transportr/files/55168/file.zip)

**Comment by grote** [comment] 2016-05-01 16:03
Are you still having this issue? The log you posted stops exactly before I would expect interesting things. Are you sure it is from the time where no directions were found?

**Comment by grote** [comment] 2016-05-01 16:10
Ok I now could reproduce it myself. I am getting this error:
```
D/de.schildbach.pte.AbstractHafasProvider: Hafas error: 13
```
whatever that means. If this is actually a problem for you, you could open an issue with [public-transport-enabler](https://github.com/schildbach/public-transport-enabler/).

I'll close this one here, because it is not directly related to Transportr. When fixed in PTE, it will be fixed in Transportr as well.

**Closed by grote** 2016-05-01 16:10 UTC
Labels: needs info, upstream
