### ISSUE TITLE
BcProvider: SkyTrains lack Product information cause NPE

### ISSUE THREAD

**Issue by jaller94** [grote/Transportr#466] opened 2018-07-19 20:37 UTC
Android: LineageOS 15.1 Nightly (Android 8.1)
App version: 2.0 (F-Droid)

The recently added network of British Columbia, Canada includes Vancouver’s SkyTrains.
When clicking on the Refresh icon in trip details which include a SkyTrain (`EXPO SKYTR`, `CANADA LIN`, and `MILLENNIUM LINE`) the app crashes.

![screenshot_transportr_20180719-133905](https://user-images.githubusercontent.com/10872136/42969142-165bedb2-8b5a-11e8-923c-6446b90ff27e.png)

Example Trip:
  * From: Abbott Street 663
  * To: Terminal Avenue 195
  * Pick a trip which includes `EXPO SKYTR`

Screen recording:
https://cloud.chrpaul.de/index.php/s/4G5GipktAqpyxje

**Comment by grote** [comment] 2018-07-19 21:35
Thanks! I can reproduce:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Enum.getClass()' on a null object reference
        at java.util.EnumSet.typeCheck(EnumSet.java:395)
        at java.util.RegularEnumSet.add(RegularEnumSet.java:161)
        at java.util.RegularEnumSet.add(RegularEnumSet.java:150)
        at de.schildbach.pte.dto.Trip.products(Trip.java:227)
        at de.grobox.transportr.trips.detail.TripDetailViewModel.reloadTrip(TripDetailViewModel.kt:110)
        at de.grobox.transportr.trips.detail.TripDetailFragment.onMenuItemClick(TripDetailFragment.java:110)
        at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:203)
```

**Comment by grote** [comment] 2018-07-19 21:36
Btw. reloading doesn't do much for this provider as it doesn't support real-time information anyway.

**Comment by jaller94** [comment] 2018-07-19 21:41
Thanks for the verification.

**Comment by grote** [comment] 2018-07-19 21:41
This is ultimately an upstream issue: This library accesses a `null` property https://github.com/schildbach/public-transport-enabler/blob/master/enabler/src/de/schildbach/pte/dto/Trip.java#L227

**Comment by grote** [comment] 2018-07-19 21:47
Another issue is that the API doesn't know the transportation product. It shouldn't be `null`. @chimo maybe you can look into this one?

**Comment by grote** [comment] 2018-07-19 21:51
@jaller94 maybe you can submit a PR to the public-transport-enabler library fixing this `null` issue generally?

**Comment by jaller94** [comment] 2018-07-19 21:55
I will try to. 👍 Maybe @anjandev can help me.

**Comment by grote** [comment] 2018-09-15 15:36
> I am able to clone the public-transport-enabler repository and add my changes. However, I am uncertain about how to import a local dependancy (my modified public-transport-enabler) into build.gradle for transportr. I have tried googling and researching for the past two days and I keep getting errors syncing my build.gradle.

I suggest you don't test with Transportr directly, but add a live test for your fix to PTE here:

https://github.com/schildbach/public-transport-enabler/blob/master/enabler/test/de/schildbach/pte/live/BritishColumbiaProviderLiveTest.java

You find more examples in the other live tests. The [ParisProvider](https://github.com/schildbach/public-transport-enabler/blob/master/enabler/test/de/schildbach/pte/live/ParisProviderLiveTest.java) has lots of tests.

**Comment by grote** [comment] 2018-09-15 15:36
@anjandev :arrow_up:

**Comment by anjandev** [comment] 2018-09-15 22:16
@grote thank you for this. I will look into adding live tests for Vancouver this week. Do you know how I can run the live tests from android studio? Messing around with gradle's version in my distro is a pain and I would rather have android studio handle the gradle distribution.

**Comment by ialokim** [comment] 2020-09-06 15:08
According to upstream https://github.com/schildbach/public-transport-enabler/pull/226 this should be resolved. @anjandev @jaller94 I'm not able to find the stations written above as example at all. Could you please test whether the issue still persists or is indeed fixed in Transportr too?

**Comment by ialokim** [comment] 2023-11-12 22:56
We had to remove BritishColombia with #884 since data for it is no longer available.

**Closed by ialokim** 2023-11-12 22:56 UTC
Labels: bug 🐞, upstream 🏞️, needs info ℹ️
