### ISSUE TITLE
Add support for Montreal (and other cities in Quebec)

### ISSUE THREAD

**Issue by baldurmen** [grote/Transportr#144] opened 2016-01-12 03:20 UTC
It looks to me that Montreal and quite a few other cities in the province of Quebec in Canada are on Navitia: https://navitia.opendatasoft.com/explore/dataset/ca-qc/table/

Having Montreal support would be great. Having all the cities supported by Navitia in Quebec would simply be awesome.

**Comment by grote** [comment] 2016-01-12 12:23
That would indeed be great. Would you like to help with that? Maybe have a look at what @kalon33 did in #137. The first step is to submit a PR to public-transport-enabler, then get it merged there. Afterwards, adding it to Transportr is fairly simple.

**Comment by grote** [comment] 2016-03-04 22:38
@chimo wouldn't this be a nice thing for you to do? ;)

**Comment by chimo** [comment] 2016-03-04 22:59
Sure! I'll probably have some free time for this tomorrow  :)

**Comment by chimo** [comment] 2016-03-05 02:13
Step 1: https://github.com/schildbach/public-transport-enabler/pull/76

**Comment by baldurmen** [comment] 2016-03-10 21:57
@chimo 's commit has been merged! What is the second step?

**Comment by chimo** [comment] 2016-03-10 22:00
2nd step would be to add it to transportr, kinda like this: https://github.com/grote/Transportr/commit/d8f4ccb2e392575d6596f45d4c87447658866107

**Comment by anarcat** [comment] 2016-03-24 19:56
anybody working on the next steps here?

**Comment by chimo** [comment] 2016-03-24 22:20
Yep, it's done. I'm guessing it'll be available in the next release. Or you can get the feature now if you compile it yourself.

**Comment by anarcat** [comment] 2016-03-24 22:30
oh i see, sorry, thanks.

**Comment by grote** [comment] 2016-03-24 22:51
I am working on some major refactorings at the moment. Once that is done, I will release a beta version in this repository: https://grobox.de/fdroid/
This will also include support for Quebec.

**Comment by anarcat** [comment] 2016-03-25 13:58
@grote please do let us know, can't wait to try th is out!

**Comment by grote** [comment] 2016-03-31 22:30
A pre-release has just been made available and can be obtained via F-Droid from his repo: https://grobox.de/fdroid/
Please file any issues you find with that release.

Issues specifically with Quebec data should be filed against public transport enabler directly.

**Closed by grote** 2016-03-31 22:30 UTC
Labels: beginner job, coverage, enhancement, upstream

**Comment by anarcat** [comment] 2016-03-31 22:46
@grote - i can confirm routing seems to work after checking a few connections. thanks, that is a great addition!

i did get a crash when fiddling around with the home location, but i do not know if it is related...?

**Comment by grote** [comment] 2016-03-31 23:06
Could you try to reproduce the crash and get a stack trace for me?

**Comment by anarcat** [comment] 2016-03-31 23:09
unfortunately, i can't reproduce it anymore. by the time i figured out how to do a screen recording (`adb shell screenrecord`), it stopped. it was triggered when i would zoom into my location using the map view and hold to set the location.

**Comment by grote** [comment] 2016-03-31 23:14
Better than screenrecord is `adb logcat` which gives me all I need to fix crashed.

Did the crash happen just when you long pressed or when you clicked something afterwards? But how's that related to the home location? At the moment, you can not set arbitrary locations as your home from the map.

**Comment by baldurmen** [comment] 2016-03-31 23:18
I've been playing around with the app for a few minutes and I haven't
seen anything wrong with it.

Thanks a lot for your work!

**Comment by anarcat** [comment] 2016-03-31 23:20
@grote yeah, i know about logcat, it's just it is difficult to describe exactly what happened and i wanted to learn how to do screen recording anyways. :) i think the crash happens when i long-press. and it's when i choose a starting point for a route.

it would be great to set arbitrary locations for home - is there an issue i can follow for that? :)

**Comment by grote** [comment] 2016-03-31 23:23
@baldurmen Thanks for testing! :)

@anarcat Thanks, let's move the discussion about this crash into #169.

The issue for arbitrary home locations is #32.
