### ISSUE TITLE
São Paulo (SPtrans) is broken

### ISSUE THREAD

**Issue by ajudator** [grote/Transportr#442] opened 2018-04-29 16:47 UTC
Hello! First of all, I am extremely happy with the idea of the project.

Testing it in Sao Paulo, version 1.1.9 and 2.0.0-rc2, I found that it doesn't work, even if it is theoretically covered with a [valid database](https://navitia.opendatasoft.com/explore/dataset/br/table/?sort=type_file). 
I tested
- going to a place A, where there is a bus line, to B, a place close to the end of the line.
- between two stops (terminals). I read the #441 , and also tried multiple denominations and platforms (that doesn't matter in fact, actually, but that's another thing).
- and stop (terminal) to a place C - the start and end of a existent line.
![image](https://user-images.githubusercontent.com/12880655/39408875-ab9eb5ee-4bcc-11e8-99bc-fde05018d061.png)
 
None of them gave results. The first and only one to return my search suggested that I walked between place A-B (apx. 1 hour).

In the 2.0.0-rc2 I also tried the (cool) Departures feature in a stop (a platform within a terminal, if there is any difference) and in some other stops. None of them returned any information. 
![image](https://user-images.githubusercontent.com/12880655/39408879-b6c01076-4bcc-11e8-9731-eca130e560e5.png)

If there is anything that I can do to help, I'd be glad to!

**Comment by grote** [comment] 2018-04-29 16:55
That's strange. I think the problem is with Navitia (they provide the API for Sao Paulo). You can [reach out to them](https://groups.google.com/forum/#!forum/navitia) and ask them what's going on.

**Comment by ajudator** [comment] 2018-04-30 16:13
[apparently](https://groups.google.com/forum/#!topic/navitia/ACsftAT70RI) their dataset is outdated.

**Comment by grote** [comment] 2018-05-09 15:08
Should be fixed now.

**Closed by grote** 2018-05-09 15:08 UTC
Labels: bug 🐞, coverage 🗺️, upstream 🏞️
