### ISSUE TITLE
wheelchair access

### ISSUE THREAD

**Issue by harvey186** [grote/Transportr#606] opened 2019-05-07 15:28 UTC
I'm a wheelchair driver and I need to know if the vehicle (bus, train and so on] is wheelchair accessable. This information is available,  because the app ÖBB Scotty is able to show it.

Please include this information also.

**Comment by grote** [comment] 2019-05-07 15:36
This ticket is a duplicate of #534

**Closed by grote** 2019-05-07 15:36 UTC
Labels: duplicate ➿

**Comment by harvey186** [comment] 2019-05-07 15:38
Sorry, haven't seen

Am 7. Mai 2019 17:36:45 MESZ schrieb Torsten Grote <notifications@github.com>:

Closed #606<https://github.com/grote/Transportr/issues/606>.
