### ISSUE TITLE
Pictures per provider

### ISSUE THREAD

**Issue by xamanu** [grote/Transportr#428] opened 2018-03-11 15:50 UTC
The standard theme pictures (from London public transport, I guess...) used in Transportr feel quite strange for some cities, like Managua, where the city and it's buses look a bit different. Is it possible to submit suitable pictures for each provider?

**Comment by grote** [comment] 2018-03-11 15:57
This sounds like a duplicate of #177, but is mood, since the upcoming version 2 doesn't have this kind of pictures anymore.

**Closed** 2018-03-11 15:57 UTC
Labels: duplicate ➿, enhancement 🏗️
