### ISSUE TITLE
Open transportr with address intents

### ISSUE THREAD

**Issue by Niilos** [grote/Transportr#361] opened 2017-09-14 14:18 UTC
It would be nice if the app subscribed to address intents (I don't remember the exact intents that are concerned).
When the user click an adress in their address book, transportr could fill the destination field with it.

**Comment by grote** [comment] 2017-09-14 14:20
Related to #200

**Comment by grote** [comment] 2017-09-14 14:20
Duplicate of #230

**Closed by grote** 2017-09-14 14:20 UTC
Labels: beginner job, duplicate, enhancement
