### ISSUE TITLE
The search for Berlin (VBB) is broken

### ISSUE THREAD

**Issue by KrimaRula** [grote/Transportr#441] opened 2018-04-28 11:06 UTC
The search for Berlin (VBB) no longer works.

The search only shows the stops, but no more connections.

**Comment by grote** [comment] 2018-04-28 11:45
I can't reproduce this with 2.0.0-rc2
Can you provide steps to reproduce?

**Comment by KrimaRula** [comment] 2018-04-28 12:52
Sorry, I should have bragged about my version.

I am using version 1.1.9 of F-Droid (latest version).

The following steps do not work:
* VBB is selected
* I have selected "Airport Tegel (Airport), Berlin" as the starting point
* I have chosen "S Potsdam Hauptbahnhof" as my destination

The system then displays the results page. There only the stops are listed but no connections.

**Comment by KrimaRula** [comment] 2018-04-28 12:54
Other cities work fine. If I select DB instead of VBB, I also find connections in Berlin, but of course less.

**Comment by KrimaRula** [comment] 2018-04-28 14:00
In most cases I use saved searches. Even with new connections there is usually a place I have already visited. The system also offers this as a stored location. 

That seems to be the problem. If I rescan the locations, the system will find connections. Once a location is selected in a search that was saved, the app no longer finds connections.

If I search for both locations again, save them and then call up the newly saved search, the app finds connections.

I don't have that problem for Cologne (VRS). Older saved searches still work there.

Translated with www.DeepL.com/Translator

**Comment by grote** [comment] 2018-04-28 14:10
Thanks for getting to the bottom of this!

This is a duplicate of  #207. Sometimes the transport agencies decide to change the IDs of their stations. So the old IDs that Transportr has saved, don't work anymore. This is not easy to detect and adapt to. Clearing the app data will help as then you will start fresh with the new IDs.

**Comment by KrimaRula** [comment] 2018-04-28 14:50
Thanks for help.

**Closed** 2018-07-23 18:12 UTC
Labels: bug 🐞, duplicate ➿
