### ISSUE TITLE
missing map attribution 

### ISSUE THREAD

**Issue by dieterdreist** [grote/Transportr#665] opened 2020-02-29 18:29 UTC
In the FDroid Version there is no attribution to OpenStreetMap for the base map. Please fix.

**Versions (please complete the following information):**
 - **Transportr Version:** 2.0.8
 - **Device:** Lenovo Tablet 9,7“
 - **Android Version:** 5

**Comment by ialokim** [comment] 2020-02-29 18:31
Duplicate of #628. PRs are welcome!

**Closed by ialokim** 2020-02-29 18:31 UTC
Labels: bug 🐞
