### ISSUE TITLE
Selected transportation modes are not saved correctly

### ISSUE THREAD

**Issue by schachmat** [grote/Transportr#225] opened 2016-08-11 12:59 UTC
Heyho,

I'm running v1.1.3 from FDroid. I disabled subways in the transportation mode selection once and since then it is always disabled on app-startup, even if I enabled it again in the previous session. Also in the transportation mode selection popup the checkboxes are not labeled, there is just empty space, no text left of them. Let me know if you need a screenshot.

**Comment by grote** [comment] 2016-08-11 13:39
Hey thanks for your report!

@kas70 This bug concerns your code. Can you reproduce the bug?

> Also in the transportation mode selection popup the checkboxes are not labeled, there is just empty space, no text left of them. Let me know if you need a screenshot.

You are using the dark theme right? That's a duplicate of #209, will be fixed in next version.

**Comment by schachmat** [comment] 2016-08-11 16:59
Thanks for the fast response, looking forward to the fix. Let me know, if you need anything else.

**Comment by grote** [comment] 2016-08-11 19:12
It would help if we could reproduce the issue you are reporting. I deselected subway, selected it again, then killed the app, started it again and subway is as expected selected.

**Comment by schachmat** [comment] 2016-08-11 21:12
Try deselecting it and then killing the app before selecting it again.

**Comment by grote** [comment] 2016-08-11 21:15
Well, if you deselect it, the app remembers that you deselected it until you change it in the future. That is not a bug, but a feature that was implemented with #39.

**Comment by schachmat** [comment] 2016-08-11 21:17
See my edit above. This preference seems to only work in one direction: Only deselecting items will be persisted, but I cannot revert that.

**Comment by schachmat** [comment] 2016-08-11 21:35
Ok, I think I found the bug: https://github.com/grote/Transportr/blob/master/src/de/grobox/liberario/Preferences.java#L130

This prevents selecting all products after any have been deselected previously. I manage to reselect all but one and it will be persisted, but I cannot reselect the last one.

**Comment by schachmat** [comment] 2016-08-22 13:31
Ping. Do you need anything else?

**Comment by kas70** [comment] 2016-08-22 13:50
Hey there,
@schachmat can you please provide clear steps for reproducing your bug?

**Comment by grote** [comment] 2016-08-22 15:15
I could reproduce it now, but haven't had time to test the PR.

The line the PR removed was meant to be an optimization, but I think it indeed prevents restoring all products when some were deselected previously.

**Comment by schachmat** [comment] 2016-08-23 08:15
Indeed. I think it is best to leave out the optimization since checking if the new product set is exactly the same as the already stored set is probably more complex than just writing the new set anyway.

**Closed** 2016-08-25 01:49 UTC
Labels: bug
