### ISSUE TITLE
Screen rotation shows settings

### ISSUE THREAD

**Issue by Neptuns** [grote/Transportr#164] opened 2016-03-09 12:29 UTC
Open Settings, change language or theme and close settings. If you rotate (portrait <-> landscape)  phone instead of rotating the main screen the Settings screen is displayed again.

**Comment by grote** [comment] 2016-03-31 22:27
Thanks for reporting this!

It should be fixed by e9320135b and is available as a pre-release here: https://grobox.de/fdroid/
Can you verify that the issue is solved with that version?
Please also report similar issues you find with that version!

**Closed by grote** 2016-03-31 22:27 UTC
Labels: bug
