### ISSUE TITLE
Drawing errors after going back from trip detail screen with Android 7

### ISSUE THREAD

**Issue by maninthemiddle01** [grote/Transportr#285] opened 2016-12-28 11:11 UTC
Thank you for this awesome app :)
I am using a moto g 2014 thea with cm 14.1. The issue is as follows: If I search for a train connection, it shows me the overview of all found train connections. When I click for detailed view, everything works fine as well. But going back to the overview of found train connections, it will show me only the previous selected one and also those new ones you get, when you pull the screen up or down to get earlier or later connections.
This I could reproduce for Deutsche Bahn and BVG, and I guess, also with other networks.
I had the feeling, that in previous versions of the app the bug did not appear, but tried it with Version 1.1.4 and Version 1.1.6, which both of them behave the same way.

![bug](https://cloud.githubusercontent.com/assets/12028992/21520700/acfaa7be-ccf6-11e6-9bf5-e4055efeff44.png)

**Comment by grote** [comment] 2016-12-28 11:15
Might be related to the reverse scene transition animation if I understood the problem correctly. I have never seen this myself.

@ByteHamster any ideas?

**Comment by maninthemiddle01** [comment] 2016-12-28 12:10
also the title bar of the application is gone (or blank white)

**Comment by ByteHamster** [comment] 2016-12-28 13:13
Have never seen that too. I will try to re-add the CoordinatorLayout, maybe the random scrolling thing is fixed now. That's the only thing that I can think of... 

https://github.com/grote/Transportr/pull/104

**Comment by ByteHamster** [comment] 2017-01-02 17:18
I can't build with all that `dependencyVerification` lines in the gradle files -.- Are those really needed?

Scrolling is still strange when switching back to `CoordinatorLayout` (you scroll away the title bar first and then get pull-to-refresh. That feels "jumpy". Additionally, you can swipe up the title bar - it goes away and never comes back).

==> I have no idea what might cause your issue and my attempt in fixing it failed. Sorry.

**Comment by grote** [comment] 2017-01-02 17:20
> I can't build with all that dependencyVerification lines in the gradle files -.- Are those really needed?

Yes, they verify that the external dependencies are actually what they should be and that nobody is for example trying to introduce a backdoor by MITMing a library download.

If you get a verification error, some library you have is different from the one I have which is cause for concern and investigation.

> ==> I have no idea what might cause your issue and my attempt in fixing it failed. Sorry.

Thanks for trying!

If we have no way to reproduce it, there is little we can do.

**Comment by ByteHamster** [comment] 2017-01-02 18:23
> If you get a verification error, some library you have is different from the one I have which is cause for concern and investigation.

I don't exactly know what happened here... Just added the verification again and the build worked... Maybe it happened because of Intellij trying to generate checksums of files that were not yet downloaded.

**Comment by grote** [comment] 2017-01-07 15:21
I don't have a Android 7.1 device to test this. Maybe it happens only with that Android version?

**Comment by TheLastProject** [comment] 2017-01-07 15:22
For me it worked fine on CyanogenMod 13 (Android 6) but not on CyanogenMod 14.1 (Android 7.1.1), so it's very likely it's broken with a change in Android itself

**Comment by kirschner** [comment] 2017-01-08 19:53
I have the same issue on Android 7.1.1 Never had this problem before on previous Android versions.

**Comment by motatuc** [comment] 2017-01-20 16:39
I am affected as well. Unfortunately logcat shows nothing helpful. Anything affected users can provide to solve this?

**Comment by grote** [comment] 2017-01-20 16:45
Only thing at the moment is to search the wide internet to see if this issue is documented somewhere else, ideally with a hint for how to solve that.

It is likely to show up in bug trackers of other Android apps and the Android bug tracker.

**Comment by motatuc** [comment] 2017-01-23 11:41
I couldn't find anything on the internet. Also because I am not really sure what to look for.
If you could explain a bit more what you think causes the problem I might be able to find similar problems.

Or, eventually, you might upgrade to android 7 to have the problem first hand :)

**Comment by ByteHamster** [comment] 2017-01-23 13:29
Might be related:

https://code.google.com/p/android/issues/detail?id=211678

**Comment by motatuc** [comment] 2017-01-24 14:33
@ByteHamster, thanks for looking into this.

Do you see any chance for fixing this?

(Just to have a visual impression, I added a screencast of the problem.)

[Screencast.avi.zip](https://github.com/grote/Transportr/files/726929/Screencast.avi.zip)

**Comment by grote** [comment] 2017-01-28 17:42
I will disable the return transition on Android 7.1 in the hope that it helps.

Please try the soon to be released beta and report back!

**Comment by grote** [comment] 2017-02-01 15:37
Nobody tried the beta and can tell me whether this is fixed or not?

**Comment by TheLastProject** [comment] 2017-02-01 15:48
I just tried 1.1.7-beta1 from the testing repo and unfortunately it's still broken

**Comment by TheLastProject** [comment] 2017-02-01 16:11
On that note, one thing I noticed on the current F-Droid stable is that in some situations the return animation draws correctly (I believe it happens if Transportr is active and a route is being shown when the device is locked and not unlocked for several minutes). Unfortunately I've not been able to reliably reproduce it working on Android 7 ever.

**Comment by motatuc** [comment] 2017-02-01 19:14
I wanted to try the beta as well but I could not get it to build. It gives me:
>Warning: License for package Solver for ConstraintLayout 1.0.0-beta4 not accepted.
You have not accepted the license agreements of the following SDK components:
     [Solver for ConstraintLayout 1.0.0-beta4, ConstraintLayout for Android 1.0.0-beta4].
     Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manage

How to accept the license? I do work with gradle and terminal only...

**Comment by grote** [comment] 2017-02-01 19:33
@motatuc That is a known issue. Check out the .travis.yml file for a workaround.

But you don't need to build it yourself just for testing. There are beta builds: https://transportr.grobox.de/#testing_beta

**Comment by motatuc** [comment] 2017-02-02 10:15
@grote 
Thanks for the tip with .travis.yml. Set it up correctly now.
But build fails for another reason:

>src/de/grobox/liberario/networks/NetworkProviderFactory.java:60: error: cannot find symbol
        private static Reference<VmtProvider> vmtProviderRef;

and

>src/de/grobox/liberario/networks/NetworkProviderFactory.java:76: error: cannot find symbol
        private static Reference<NegentweeProvider> negentweeProviderRef;

**Comment by grote** [comment] 2017-02-02 10:39
@motatuc sounds like a case for `git submodule update` maybe?

**Comment by grote** [comment] 2017-02-02 10:40
Oh and looks like you try to build master (v2) and not the v1 branch that you want to test.

**Comment by motatuc** [comment] 2017-02-02 11:05
Thanks for these suggestions!

Build finished, but unfortunately I can confirm that the problem still persists in 1.1.7-beta1.

**Comment by motatuc** [comment] 2017-02-04 17:07
Problem is gone in 1.1.7 final. However the transitions are (of course) not nice anymore. A pity.

**Comment by grote** [comment] 2017-02-04 23:26
I am happy to bring them back to Android 7.1 if someone solves the nasty issue with the return transition.

**Closed** 2017-02-04 23:27 UTC
Labels: bug, needs info
