### ISSUE TITLE
Character encoding problem

### ISSUE THREAD

**Issue by Vierer** [grote/Transportr#490] opened 2018-07-28 12:44 UTC
Germany, KVV

![screenshot_20180728-144104](https://user-images.githubusercontent.com/23013069/43356621-5dc66d14-9274-11e8-965c-a6ff868cd924.png)

**Comment by grote** [comment] 2018-07-28 13:30
Essentially a duplicate of #452 even when for a different provider

**Closed** 2018-09-04 10:59 UTC
Labels: duplicate ➿
