### ISSUE TITLE
Date Format wrong under some circumstances

### ISSUE THREAD

**Issue by h-2** [grote/Transportr#115] opened 2015-10-31 18:24 UTC
Date is displayed as 10.31.2015 which confuses me no end! Isn't behavior like this controlled system-wide?

**Comment by h-2** [comment] 2015-10-31 18:26
If it is not possible to easily localize, can we instead use ISO dates, I.e. 2015-10-31 ?

**Comment by grote** [comment] 2015-10-31 18:26
Yes it is and Transportr should respect this. Where do you see the wrong date? Could you please provide screenshots of the wrong date and your system date format setting?

**Comment by TheLastProject** [comment] 2015-10-31 18:27
On my Android phone, which is configured to use British English, the date in the Directions screen is shown as 31/10/2015. If I set my phone to German, it uses 31.10.2015. I'm assuming something is indeed misconfigured on your phone, as it works fine on mine.

**Comment by h-2** [comment] 2015-10-31 18:31
![img_20151031_192810](https://cloud.githubusercontent.com/assets/2996863/10865245/d7f5e5ee-8005-11e5-967d-0053dd2373e2.jpg)

I have no issues in other apps like the gallery...

**Comment by TheLastProject** [comment] 2015-10-31 18:32
What is your exact language? There are a fair bit of German settings.

**Comment by h-2** [comment] 2015-10-31 18:37
Its Deutsch (Deutschland) and linke I said, I am am seeing correct dates in other apps (although most apps abbreviate the month with three letters so its obvious).

**Comment by grote** [comment] 2015-10-31 18:50
After switching my phone to Deutsch (Deutschland), the button text is not updated properly. However, after killing the app and starting it, the text is alright (31.10.2015).

It should also be fine according to the code:
https://github.com/grote/Transportr/blob/master/src/de/grobox/liberario/utils/DateUtils.java#L307
https://github.com/grote/Transportr/blob/master/src/de/grobox/liberario/utils/DateUtils.java#L43

Maybe try changing the language to English, then back to German and then restarting the app?

**Comment by h-2** [comment] 2015-10-31 18:57
If i change it to Britisch english, than it is displayed as 10/31/2015 which is wrong as well, or not? Changing back to German produces 10.31.2015 again...

**Comment by h-2** [comment] 2015-10-31 19:00
![screenshot_2015-10-31-19-54-15](https://cloud.githubusercontent.com/assets/2996863/10865396/e819fa60-8009-11e5-82a5-a243d8d5bf56.png)

Proof that other apps work fine :)

**Comment by grote** [comment] 2015-10-31 19:12
I did some research and it looks like what I am doing in https://github.com/grote/Transportr/blob/master/src/de/grobox/liberario/utils/DateUtils.java#L47 is the way to go. I don't know why this doesn't work for your device/OS. Maybe you can dig into the source of these other apps and see what they do differently.

**Comment by grote** [comment] 2016-03-31 22:29
This might have been fixed by e932013 which is in a pre-release available here: https://grobox.de/fdroid/
Can you verify that the issue is solved with that version?

**Comment by grote** [comment] 2016-05-01 14:13
Closing this due to no feedback for a month. I consider it fixed.

**Closed by grote** 2016-05-01 14:13 UTC
Labels: bug, needs info
