### ISSUE TITLE
Problem with With Wiener Linien

### ISSUE THREAD

**Issue by pwnage-pineapple** [grote/Transportr#135] opened 2015-12-07 22:49 UTC
When attempting to search for a route using Wiener Linien, the search fails and this popup appears: http://tinypic.com/r/23vyquq/9

**Comment by grote** [comment] 2015-12-07 23:17
I can confirm this problem. Wiener Linien changed their API. This needs to be fixed within [/schildbach/public-transport-enabler](/schildbach/public-transport-enabler).

**Comment by grote** [comment] 2015-12-31 16:53
This problem is apparently caused by the Wiener Linien company itself and can not be solved by us. Somebody needs to contact them and let them know about this problem with their server.

**Comment by grote** [comment] 2016-03-04 22:37
Problem was fixed by Wiener Linien company now.

**Closed by grote** 2016-03-04 22:37 UTC
Labels: bug, coverage, upstream
