### ISSUE TITLE
Can't enter FROM while using Germany-VRN in a direct way

### ISSUE THREAD

**Issue by AndroidUserGermany** [grote/Transportr#415] opened 2018-01-29 23:48 UTC
On Galaxy S8+ I installed TRANSPORTR freshly. Then I have choosen Germany and then VRN. I like to find a proper transportation between FROM and TO and therfore I like to enter a FROM station. 
Issues:
a) An existing station name is not accepted.
b) Instead in the list of entered station appears now 'Trittenheim, Auf de ....' which seems to come from nowhere.

When choosing in the menu stations nearby and picking the option search on map,  clicking there the wished station for a longer time an option box comes up where I pick option stations nearby. In that list I pick the proper station. In the next option box I pick FROM HERE and now the wished FROM station is in the FROM field.

Note: Once a station name got it to have been showed up in the FROM field it comes up in the list of used FROM station names.

Expected behavior:
a) it should be possible to enter an existing station name in the FROM field
b) it should be possible to pick a station directly from the map 'stations nearby'

**Comment by grote** [comment] 2018-01-30 00:43
Sounds like a duplicate of #409

**Closed by grote** 2018-01-30 00:43 UTC
Labels: bug, duplicate, v1

**Comment by AndroidUserGermany** [comment] 2018-01-30 05:42
I installed the beta version as mentioned in #409 and it works. Txs for that very fast response.
