### ISSUE TITLE
UI Concept merging recents and Directions screen

### ISSUE THREAD

**Issue by ElectricCookie** [grote/Transportr#232] opened 2016-08-30 23:00 UTC
![Mockup of screen](http://i.imgur.com/d58AujA.png)

There's not really much to say about this Mockup. I kinda felt like the Directions Fragment is kinda empty and that you could merge it with recent trips to make it quicker to travel a recent connection, since you don't have to open the nav-drawer first.

**Comment by grote** [comment] 2016-08-30 23:06
Thanks, I really appreciate good UI mockups! :)

How does that fit together with the favorite trips that are currently on the DirectionsFragment (when you add them)?

**Comment by ElectricCookie** [comment] 2016-08-30 23:10
That's a good question... Maybe display them above the recent trips? I suppose most people only have at max 3 connections as favorites and scrolling down to see a recent connection would still be quicker than switching fragment

**Comment by ElectricCookie** [comment] 2016-08-30 23:21
You could then leave out the trips that are in the favorites in the history to clean it up even more

**Comment by grote** [comment] 2016-08-30 23:26
Showing the favorites above the recent trips could work. Just technically not easy to implement if the header should leave the screen when scrolling down.

I thought of only showing a trip once as well, but then it wouldn't be a true history anymore, right? People might wonder, but I searched yesterday for that and it isn't here.

Departures and Nearby Stations both also show the results below the header and I thought about doing this at some point as well. Currently, it isn't possible though because scroll down/up to load more trips won't work then.

**Comment by ElectricCookie** [comment] 2016-08-30 23:30
I wouldn't think that it would be confusing, since it would just show up higher in the list. 

I think you can setup this layout with a coordinator layout, might look into it tomorrow.

**Comment by grote** [comment] 2016-08-30 23:32
The problem is the RecyclerView when it has heigth set to match_parent, it doesn't do fling scrolling anymore. You can add many favorite trips to reproduce.

You are welcome to try something, but please don't change the header for now, since there are still open question and it would be inconsistent with the others.

**Comment by ElectricCookie** [comment] 2016-08-30 23:39
Isn't that flinging issue caused by the app_bar_layout?

**Comment by grote** [comment] 2016-08-30 23:44
Please find out and if you manage to solve the problem, I am looking forward to your pull request! :)
I myself don't have so much time for this at the moment.

**Comment by ElectricCookie** [comment] 2016-08-30 23:44
https://github.com/henrytao-me/smooth-app-bar-layout/blob/master/README.md

 You're talking about this issue, right?

**Comment by grote** [comment] 2016-09-04 15:36
#136 is also related to this issue.

> You're talking about this issue, right? 

I'm actually not sure it is really this one.

**Comment by grote** [comment] 2017-11-01 21:16
In the upcoming Transportr v2 the directions screen looks very similar to the above one, so I am closing this ticket.

**Closed by grote** 2017-11-01 21:16 UTC
Labels: enhancement, needs info
