### ISSUE TITLE
[2.0.3] When entering destination, start location gets set as well

### ISSUE THREAD

**Issue by wonder75** [grote/Transportr#549] opened 2018-11-28 23:12 UTC
**Describe the bug**
Version 2.0.3 introduced a strange behaviour on my device.
It broke the app for me, I had to downgrade to 2.0.2.

When entering the "startng station" everything is alright. I can choose the correct "start from" station.
After that, when entering the destination, I can search for it and choose it. But the second i choose the destination, the "start from" station field is filled with the station i chose as destination.

This happens with every destination station i choose.

So after entering data i get:

Start Station: STATION I CHOSE AS DESTINATION
Destination:  STATION I CHOSE AS DESTINATION

I am using the Deutsche Bahn provider only.
Everything used to work without problems (and still does) with 2.0.2.

**Versions (please complete the following information):**
 - **Transportr Version:** [e.g. 2.0.3]
 - **Device:** [e.g. Nexus 5x]
 - **Android Version:** [e.g. Android 8.1 (Lineage)]

**Comment by grote** [comment] 2018-11-28 23:21
Fixed by #547.

I leave this open in case more people find it.

**Comment by Jowat97** [comment] 2018-11-29 03:06
@grote I have the same issue. I downloaded the newest Version (2.0.3) from the F-Droid Store. And every time I type in the Destination, this also will change the Start Station to the Destination! Exactly the same problem as @wonder75 .

Version 2.0.2, which is by the way the current version on the Google Play Store works perfectly and doesn't have this problem.

As far as I can see, @ajbruin already fixed this error: https://github.com/grote/Transportr/commit/d02ff86f5ee09db6cd95fb92766409e4fbaf9e66 #513 

You should upload the newest fixed version of F-Droid and the Play Store.

**Comment by Jowat97** [comment] 2018-11-29 03:09
@grote I have the same issue. I downloaded the newest Version (2.0.3) from the F-Droid Store. And every time I type in the Destination, this also will change the Start Station to the Destination. Exactly the same problem as @wonder75 .

Version 2.0.2, which is by the way the current version on the Google Play Store works perfectly and doesn't have this problem.

As far as I can see, @ajbruin already fixed this error: https://github.com/grote/Transportr/commit/d02ff86f5ee09db6cd95fb92766409e4fbaf9e66 #547 

You should upload the newest fixed version on F-Droid and the Play Store.

**Comment by wonder75** [comment] 2018-12-01 16:55
Hey @ogasser, this is how i downgraded using F-Droid.

- Uninstall 2.0.3
- Install 2.0.2 from F-Droid (scroll down on app page to find old versions)
- Exclude 2.0.2 from updates in F-Droid (Options -> manage installed applications -> long press on Transportr)

**Comment by ogasser** [comment] 2018-12-02 16:11
@wonder75 Thanks! The issue is that all app data (preferences etc) will be lost using this procedure.

**Comment by htgoebel** [comment] 2018-12-03 16:09
@grote May I ask you to create an bug-fix release as this bug renders Transportr 2.0.3 useless for all thoas using the from--to method. I've seen this fix is only scheduled for release 2.1 which waits for "Dark theme with light map design".

Nobody else reported this before since it worked fine in 2.0.2.

**Comment by grote** [comment] 2018-12-03 16:22
The fix will be part of the next release which I'll do once I find the time for it.

**Comment by grote** [comment] 2018-12-09 14:34
Closed by  75ac04e

**Closed by grote** 2018-12-09 14:34 UTC
Labels: bug 🐞
