### ISSUE TITLE
NS does not support GPS positions

### ISSUE THREAD

**Issue by TheLastProject** [grote/Transportr#102] opened 2015-10-23 21:08 UTC
When choosing "Use Current Position" anywhere in the app while using NS, a toast with the following error appears (I have substituted my GPS coordinates with <LOC> in this error):

`IllegalArgumentException: cannot handle: Location{ADDRESS,<LOC>, place=GPS,name=<LOC>}`

**Comment by TheLastProject** [comment] 2015-10-23 21:13
Use Current Position also causes an error toast in "Directions". NS is so broken.

**Comment by grote** [comment] 2015-10-24 14:36
I am sorry, but you will have to take this upstream again. There's not much I can do here. If you know how to program, you can try improving the NS provider upstream.

**Comment by TheLastProject** [comment] 2015-10-24 14:38
Upstream improving NS would be the nicest, but until that time, it would probably be good to disable GPS for NS so that Transportr doesn't show UI elements that don't work.

On 24 October 2015 16:36:24 CEST, Torsten Grote <notifications@github.com> wrote:
>I am sorry, but you will have to take this upstream again. There's not
>much I can do here. If you know how to program, you can try improving
>the NS provider upstream.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/grote/Transportr/issues/102#issuecomment-150823459

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by grote** [comment] 2015-10-24 14:41
Sorry, but there's no mechanism to disable GPS for certain providers. There are capabilities, but these do not include GPS for location searches. Adding this capability would need to be done upstream in PTE again. For now, the error messages are not great, but good enough.

**Comment by grote** [comment] 2015-10-27 22:22
The issue is reported upstream. When fixed there, it will automatically get fixed here with the next library update. So I will close this issue, because there is no point in keeping it open here as well.

**Closed by grote** 2015-10-27 22:22 UTC
Labels: bug, upstream
