### ISSUE TITLE
9292 doesn't find trips from GPS locations

### ISSUE THREAD

**Issue by TomJansen** [grote/Transportr#527] opened 2018-09-17 11:11 UTC
**Describe the bug**
Every first time I search for directions, the app says it cannot find the 'from' location. But when I enter the search a second time, it works and gives me the data. I don't know if I should report it to public-transport-data or here, but because it always happens the first time, I think it is a issue with Transportr. Sorry if this is not the case.

**To Reproduce**
1. Search for a location from the main screen.
2. Press the red floating search button
3. You see the 'from' location error
4. Click on from location and select another adress nearby
5. It works and gives the directions.

**Versions (please complete the following information):**
 - **Transportr Version:** 2.0.2
 - **Device:** Samsung S4
 - **Android Version:** 7.1.2 (LineageOs microg)

**Comment by grote** [comment] 2018-09-17 13:55
Sorry, but I can't reproduce the behavior. Can you please provide a transportation network and search keyword that allows me to reproduce it?

**Comment by TomJansen** [comment] 2018-09-17 16:05
9292 as search network, `station Delft` as search. I think it has something to do with Transportr receiving the 'from' location from GPS.

**Comment by full-duplex** [comment] 2018-09-17 23:02
I was able to reproduce this consistently by manually setting from/to to a coordinate by holding down a random location on the map.

https://github.com/schildbach/public-transport-enabler/pull/225 should fix this bug and also add direct support for using coordinates in trip queries.

**Comment by grote** [comment] 2018-09-18 10:39
Awesome, thanks for the quick fix! :)

**Comment by full-duplex** [comment] 2018-09-21 01:16
The fix was merged upstream.

**Comment by grote** [comment] 2018-09-21 02:02
Thanks, I'll include it in the next release!

**Comment by grote** [comment] 2018-11-25 14:02
Fixed in ffaa789b2d9a73d06fe1c66d45a214f15a38ce37

**Closed by grote** 2018-11-25 14:02 UTC
Labels: bug 🐞, upstream 🏞️
