### ISSUE TITLE
Possibility to show on start screen "recent connections"

### ISSUE THREAD

**Issue by dktzde** [grote/Transportr#170] opened 2016-04-04 17:48 UTC
Hi, for me it would be fine, to have the possibility to change what is shown on the start screen. 
At the moment there are my "favorite trips". Sometimes I would like to change it to "recent trips" (maybe the last 3 or 5 trips). Maybe it could be possible to change it in the settings.

**Comment by grote** [comment] 2016-04-04 18:55
This would be a tricky UX challenge to solve. There's also #136 open. I'm open for suggestions on how to solve that.

**Comment by grote** [comment] 2016-09-04 15:34
I'll close this as a duplicate of #232 since this one is more advanced.

**Closed by grote** 2016-09-04 15:34 UTC
Labels: enhancement, needs info
