### ISSUE TITLE
RuntimeException: LOCATION HCI Service: missing or invalid.

### ISSUE THREAD

**Issue by Avispa** [grote/Transportr#366] opened 2017-10-05 16:10 UTC
When I try to look up a connection via BVG (Berlin public transp.), I get ´RuntimeException: LOCATION HCI Service: missing or invalid.´ even though I get the station suggestions while typing just fine.

Looking for connections on the italian train service does not bring up this error and seems to work fine. Even though the suggestions while typing the stations name doesn't work well.

However I am not 100% sure if the problem is on my side, since I maybe disabled some google apps/services even though it doesn't appear to be a problem.

**Comment by grote** [comment] 2017-10-05 16:27
I can reproduce the problem if I use saved location for the search. If I type and select new locations, the search works fine. Looks like the location IDs in the API have changed, so it can't find the old saved locations anymore :(

**Comment by Avispa** [comment] 2017-10-06 15:28
Yes, I can confirm the conclusion.
When I use two stations I used never before, lookup works just fine -- just wasn't easy to find two. ;)

Is there a way to refresh the IDs preferable without losing the type/station cash?

**Comment by grote** [comment] 2017-10-06 15:31
Sorry, I don't know how to deal with this problem. Help is appreciated.

**Comment by grote** [comment] 2017-10-06 15:32
Related to: #207

**Comment by Avispa** [comment] 2017-10-13 01:30
I addtion: even though a station is known/saved already, you can avoid auto completion by "tapping" away to get into the station search screen and the connection look up works as expected. Nevertheless using the "saved" station name due to auto complete etc. it will still not work.

However it got very annoying to use so obviously and finally I "fixed" it by deleting all the data of **Transportr**. However, since it seems to happen surprisingly often -- more than never -- that (U)IDs are changing, some kind of mechanism to prevent or an option to solve this problem more sophisticated would be still appreciated.

**Comment by grote** [comment] 2017-10-13 02:29
Are you saying that even after clearing all data, you got the error again?

**Comment by dennisguse** [comment] 2017-10-14 14:09
I had the same experience using the BVG data (and 1.1.8) - I installed transportr at the beginning of this year.

Temporary solution: clearing all data; not nice, but works.

If I got it right, then transportr stores the stationID as well as the identifier while using the stationID for later queries.
And the issue seems to arise if the stationID changes (might happen sometimes).

From a brief glance into the code, I that public-transport-enabler reports the error (https://github.com/schildbach/public-transport-enabler/blob/1b10571183a8b2bf95e004d2b51467850e10baf0/enabler/src/de/schildbach/pte/AbstractHafasMobileProvider.java#L229) while the result is only evaluated in transportr if Status.OK is received (https://github.com/grote/Transportr/blob/3d4eb9d8184a0c9cbaea16d28e64e98f1b4c8bf2/src/de/grobox/liberario/departures/DeparturesActivity.java#L219) .

A workaround that comes to my mind would be to do the following (in case of INVALID_STATION): 
* Try to get the new stationID by lookup using the stored name
If  (successful retry using the new stationID) {
 retry using new station id
 if (success) {
  well done
 } else {
  Show some not confusing error message
 }
} else {
  show an error message that the station is not valid anymore and remove the stored information...
} 

@grote What do you think?

And, I think, would be nice to disable the toast message from transport-enabler as it is not useful to the user... (IMHO).

**Comment by grote** [comment] 2017-10-14 14:24
Yes, we can try something like that. However, the code you are looking at is already part of the construction site for Transportr 2. Once this will be ready, doing this should be easier.

We should probably continue this discussion in #207. Would you like to work on this once the code in question has settled down?

**Comment by dennisguse** [comment] 2017-10-14 17:44
@grote 
Yes, I am willing to join working on this.
Just let me know.
Will follow #207.

**Comment by grote** [comment] 2017-11-01 21:37
I am closing this in favor of #207.

**Closed by grote** 2017-11-01 21:37 UTC
