### ISSUE TITLE
Start and destination stops always identical

### ISSUE THREAD

**Issue by bluelupo** [grote/Transportr#554] opened 2018-12-14 13:49 UTC
**Describe the bug**
A clear and concise description of what the bug is. Note that problems related to public transport data (malformed data, missing search results, etc.) need to be reported to [public-transport-enabler](https://github.com/schildbach/public-transport-enabler/) and not here.

**To Reproduce**
1. Go to route calculation
2. See error
When entering the start and finish stop, an error occurs. The second entry or selection of the stop is taken over in both input fields, so that the start and finish are no longer different.

reproducible at any time

**Expected behavior**
see above

**Screenshots**

**Versions:**
 - **Transportr Version:** [2.0.3]
 - **Device:** [Oneplus 3T]
 - **Android Version:** [LineageOS 15.1 Nightly from 2018-12-13]

**Comment by grote** [comment] 2018-12-14 13:50
Thanks for the report. This is a duplicate of #549 and fixed in version 2.0.4 (available from Google Play beta or F-Droid).

**Closed by grote** 2018-12-14 13:50 UTC
Labels: duplicate ➿

**Comment by bluelupo** [comment] 2018-12-14 13:52
Thanks for your quickly information.
