### ISSUE TITLE
IllegalStateException cannot exceed strings table size

### ISSUE THREAD

**Issue by ajira86** [grote/Transportr#78] opened 2015-06-15 16:09 UTC
When I set SBB (Switzerland) timetable with direction from "Morges" city to "Salins, Le Parfait" bus stop, a toast message is displaying "IllegalStateException pointer 4 cannot exceed strings table size 0"

**Comment by ajira86** [comment] 2015-06-15 16:10
![tmp_8407-screenshot_2015-06-15-18-01-381672396854](https://cloud.githubusercontent.com/assets/1295025/8164506/c81a69e4-1389-11e5-9b78-d86204aa43b6.png)

**Comment by grote** [comment] 2015-06-15 17:25
Thanks for reporting! That's an issue with the [public-transport-enabler](https://github.com/schildbach/public-transport-enabler) library. Would you mind reporting the issue (ideally with a test-case) there?

**Comment by grote** [comment] 2015-10-27 22:22
The issue is reported upstream. When fixed there, it will automatically get fixed here with the next library update. So I will close this issue, because there is no point in keeping it open here as well.

**Closed by grote** 2015-10-27 22:22 UTC
Labels: bug, upstream
